### ISSUE TITLE
Clarify mongodb requirement

### ISSUE THREAD

**Issue by micahjsmith** [sintel-dev/Orion#181]
The documentation [says](https://signals-dev.github.io/Orion/getting_started/install.html#mongodb),

> In order to be fully operational, Orion requires having access to a MongoDB database running version 3.6 or higher.

But you can currently install Orion without having mongo installed nor running.

Possible actions:

* clarify in the documentation what it means to be "fully operational", which clearly does not preclude the user from detecting anomalies using the sample code
* add minimal instructions for using mongo with orion
* optional: separate out the pymongo/mongoengine stuff as an extra, i.e. `orion-ml[db]`
* optional: create a dockerfile or docker compose stack (or other deployment format) for easily running orion with the db attached

**Comment by sarahmish** [comment]
Clarified the meaning of "fully operational" in the documentation.
I will keep this issue open to explore how we can improve the usage of `mongodb` in Orion.

**Comment by sarahmish** [comment]
Closing, `mongodb` is no longer a requirement for Orion since [PR #272](https://github.com/sintel-dev/Orion/pull/272)
