### ISSUE TITLE
Conflict when install orion-ml (can't uninstall llvmlite)

### ISSUE THREAD

**Issue by vkehfdl1** [sintel-dev/Orion#207]
* Orion version:0.1.7.dev0
* Python version: 3.7.9
* Operating System: Ubuntu 18.4 LTS

### Description

When I tried to install orion-ml using pypi "pip install orion-ml." 
There was an error said "ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

### What I Did

I did lost of things, but final solution was manually delete llvmlite files. I went to the site-packages directory and delete all llvmlite files and directories. Because there was an error when pypi tried to remove llvmlite. 
But I can't uninstall llvmlite with "pip uninstall llvmlite" There is an error in that command. 

So this issue is solved, but you can take a look about llvmlite uninstall. Thanks for amazing library for anomaly detection!

**Comment by sarahmish** [comment]
Hi @vkehfdl1, thanks for the note!

I normally recommend creating a separated environment and working from their to avoid any problems. 

`llvmlite` is a dependency of `numba` which was recently added. Based on the suggestion here https://stackoverflow.com/questions/58766671/cannot-install-librosa-python-how-can-i-uninstall-llvmlite
a solution might be `pip install orion-ml --user` and hopefully it works!

**Comment by marycotter** [comment]
I ran into exactly the same issue as vkehfdl1.

I found a suggestion to use pip with ignore-installed and it worked for me:
pip install llvmlite --ignore-installed
