### ISSUE TITLE
Feeding HDF5 Files into Orion-ML and Large Directories and Subfolders.

### ISSUE THREAD

**Issue by NIckyVNYC** [sintel-dev/Orion#257]
* Orion version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Hi, I have large time series data in many HDF5 file that are in directories and subfolders.  I am stuck trying to figure out how to feed it into Orion-ML.   I was able to get Orion-ML to work on my Mac.  Any suggestion on what to use to feed multiple HDF5 files in folders and subfolders into ORION-ML?  Thanks. 
![2021-11-01 at 22 35](https://user-images.githubusercontent.com/67718014/139777651-2527fc90-54ff-4fde-855e-519ff590aa35.jpg)
This is what an example of the time series looks like. 
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, you can feed your data one signal at a time. I recommend using panda's [HDF5 reader](https://pandas.pydata.org/docs/reference/api/pandas.read_hdf.html) to load it into python, then you can invoke Orion as shown in the quickstart example.

I recommend reading [how to use pipelines on custom data](https://sintel.dev/Orion/user_guides/primitives_pipelines/pipelines.html#pipelines-for-custom-data) to help you configure a pipeline to your dataset!

**Comment by NIckyVNYC** [comment]
Thank you for your answer.  That is very helpful.  I was able to use the H5PY library and OS.walk to go through all the folders and the files to put it into Orion.   Also, I  have my program taking the data from each file and changing it to a  CSV file with just 2 columns in each files the columns called "timestamp" and "value."  I figured if it was the same as the sample data that Orion-ML gives it would less likely have a problem.   

Now I have to figure out how to change the hyperameters shape of the array I am feeding because I am  having this problem:  "  shape = np.asarray(X)[0].shape IndexError: index 0 is out of bounds for axis 0 with size 0." 

What is interesting is that the CSV file that I am putting in isn't that different than the the Orion-ML sample data from the website that works on my computer, like "A-1-Test.csv."  One difference is that with the Orion-ML sample data Orion is going through looking for anomalies through one column in one file .  But for my research, I want Orion-ML to compare one column of values over time in one file, compared to a column in another file, etc.   So I guess I need to read up more on the Hyperameters for Orion-ML and the Pipelines on custome datas.  I guess I need to tweak the "shapes" of the arrays that I am putting into Orion-ML.  Thanks again for helping me. This is very helpful and it is a very interesting GANs program.  Best, Nicholas .

**Comment by sarahmish** [comment]
Thanks @NIckyVNYC, I think you are running into a similar issue https://github.com/sintel-dev/Orion/issues/162#issuecomment-763731339

> I recommend reading [how to use pipelines on custom data](https://sintel.dev/Orion/user_guides/primitives_pipelines/pipelines.html#pipelines-for-custom-data) to help you configure a pipeline to your dataset!

The documentation above will help you resolve `IndexError: index 0 is out of bounds for axis 0 with size 0.` error
