### ISSUE TITLE
How to Adjust Pipeline and Parameters To Compare timeseries between thousands of separate files.

### ISSUE THREAD

**Issue by NIckyVNYC** [sintel-dev/Orion#258]
* Orion version: :Latest
* Python version: 3.61
* Operating System: Unix

### Description

Looking for any suggestion how to solve this problem:  I am trying to use Orion-ML to look for anomalies between separate files.  I am able to feed separate files (thousands and thousands) each with separate time series (about 1700 to 1900 rows) but I think that Orion-ML is looking for anomalies within each separate files.  I want to Orion-ML to find the files that have time series that don't look like the normal time series on the majorities of the files.   Is there a way for the Pipelines and parameters to be tweaked to compare one file's long times series to another file with time series, and if the time series is very different than the other time series, than that is an anomaly?    

### What I Did

I tried tweaking the "interval" for the Hyperparameter for custom data.  But interesting if I put a number above number 2, it crashes the programming with this: "IndexError: index 0 is out of bounds for axis 0 with size 0".  Only 1 and 2 work. This is strange, because each file has time series rows of 1 to 1800 or 1 to 1900 etc.    Note each time stamp is just 1, 2, 3 ..... ..  up to 1800 for the row.   Not sure if this is the right way to change a parameter to compare one file with a time series to other files with time series. 

Any suggestions would be helpful.  

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.


```
using any "interval" number greater than 2 causes this crash.   
Traceback (most recent call last):
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlblocks/mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlblocks/mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlprimitives/adapters/keras.py", line 98, in fit
    self._augment_hyperparameters(X, kwargs)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlprimitives/adapters/keras.py", line 89, in _augment_hyperparameters
    shape = np.asarray(X)[0].shape
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/home/nvasilescunyc/tess/orion1/main.py", line 112, in <module>
    orion_test.fit(test_data)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/orion/core.py", line 84, in fit
    self._mlpipeline.fit(data)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlblocks/mlpipeline.py", line 649, in fit
    self._fit_block(block, block_name, context)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlblocks/mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlblocks/mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlprimitives/adapters/keras.py", line 98, in fit
    self._augment_hyperparameters(X, kwargs)
  File "/home/nvasilescunyc/tess/lib/python3.6/site-packages/mlprimitives/adapters/keras.py", line 89, in _augment_hyperparameters
    shape = np.asarray(X)[0].shape
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, interesting questions I will answer each point separately

#### what "interval" value to use?
This is depends on the space between each entry in your time series. You mention that "each time stamp is just 1, 2, 3 ..... up to 1800" therefore the appropriate value of `interval` is 1. 

To explain this a bit further, when you set `interval` to 2, in your case you will shrink your time series by half. You can refer to the documentation of [time segments aggregate](https://sintel.dev/Orion/user_guides/primitives_pipelines/primitives/time_segments_aggregate.html) to understand what this primitive actually does.

#### how to compare anomalies with respect to an anchor signal?
One way to approach this with orion is to train on the anchor signal, for example signal A, and then use the trained model to detect anomalies in another signal, for example signal B. You can achieve that using our `fit/detect` Orion API.

Using this approach, you expect signal A and signal B to share the same distribution and temporal features.

**Comment by NIckyVNYC** [comment]
Hi,  I finally got seperate files to load into in Orion-ML using LSTM.  Now I am trying to use Tadgan in Orion-ML.  But I am having this problem when the data goes in to fit.  Keeps making this error:  raise ValueError("Axis {} is outside the dimensions of X ({}).".format(axis, dims))
ValueError: Axis 2 is outside the dimensions of X (1).   But here is the thing, when I feed the sample data from load_signal, 'S-1-train', that error doesn't occur.  But when I feed my data, I get that error.  Trying to figure why my data makes that error but no "S-t-train." The shape and number of axes is the same but mine guests the error.  here is the shape of the S-1-Train data compared to my data.  Looks similar and the labels for the columns are the same.  
![sampledata](https://user-images.githubusercontent.com/67718014/144321305-05476957-7e0c-40b6-8149-1fcfef0c7b18.jpeg). This is my data below.  Its the same shape and labeled similar but for some reason says Axes number is wrong.  
![mydata](https://user-images.githubusercontent.com/67718014/144321319-cc2638eb-71e7-4e30-ba10-c281367382d7.jpeg)
If you have any suggestions what I am doing wrong I would appreciate it.  By the way, when I fed these files in to the LSMT version of Orion-ML I didn't get this error on my data.  Thanks.

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, did you pass in the hyperparameter settings?

```python3
from orion import Orion

hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        "interval": 1
    },
    "orion.primitives.tadgan.TadGAN#1": {
        'epochs': 5
    }
}

orion = Orion(
    pipeline='tadgan',
    hyperparameters=hyperparameters
)
```

**Comment by NIckyVNYC** [comment]
Thank you, you are correct. That was the problem.  I didn't set up the hyperparameters corectly, 
Now its working ut this warning is coming out:

'Discrepancy between trainable weights and collected trainable'
I see there was a prior issue for Tadgan before.

**Comment by sarahmish** [comment]
Awesome! You can ignore the warnings for now :)

**Comment by NIckyVNYC** [comment]
I am getting results as it goes through files but I get this warning:  Is this something I should not worry about or should I try to fix it?   

2021-12-09 17:54:49.106749: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.

2021-12-09 17:54:49.120100: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.

2021-12-09 17:54:49.165872: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:533] model_pruner failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'loss_2/model_2_loss/mean_squared_error/weighted_loss/concat' has self cycle fanin 'loss_2/model_2_loss/mean_squared_error/weighted_loss/concat'.
2021-12-09 17:54:49.281017: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:533] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'loss_2/model_2_loss/mean_squared_error/weighted_loss/concat' has self cycle fanin 'loss_2/model_2_loss/mean_squared_error/weighted_loss/concat'.
2021-12-09 17:54:49.296242: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:533] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2021-12-09 17:54:49.308844: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-12-09 17:54:49.321398: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.

**Comment by sarahmish** [comment]
@NIckyVNYC these warnings are expected, we will fix these issues in our next update.

**Comment by NIckyVNYC** [comment]
Question, as I am "fiting" the Tadgan version Orion-ML on separate time series files, I noticed that it takes more time for each additional file.  I set it up with 3 epochs.  So for example, it takes 3 minutes for the 1st file, then 4 minutes for the second file to fit, and then 5 minutes for the third file, and so on and so on so after a while its 20 minutes for a file, and then later 30 minutes, etc.  Is this because the model that is training compares the next file to its analysis of the prior files.  So its quick on the 1st file, because it hasn't done any analysis on any prior file, but it takes longer lets say on the 20th file, because it also looks at it compared to the prior 19 files.  Am I correct?   I am trying to figure out if I can speed it up to fit (train) on lets say 1000 files.

**Comment by sarahmish** [comment]
The `fit` command is only trained using the data that was passed to it. I would relate the size of the file to the runtime and see if there is a correlation.

**Comment by NIckyVNYC** [comment]
Dear Sarah, I checked, and the data in each file is around the same each time, say about 14,000 rows.  And I tried different files, and the same thing happens with the different data in Tadgan version of Orion-ML.   At the beginning, the time from  the first file to the second file is like 2 minutes.  But after it goes to the next file, more time, so by the time it goes to the 40th file, it is taking more than 1 hour for the next file.  Continuing to grow.  Of the LSMT version of Orion, it does grow like that for each file.  Could there be a bug in the Tadgan version of Orion-ML?   Thanks

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, seems like I am running into the same issue for `tadgan`, however `lstm_dynamic_threshold` takes the same amount of time in each run.

This could be due to the fact that we "build" the model with every fit command. I will run more diagnostic tests and see where we can optimize the code.

Thank you for point out the issue!

**Comment by NIckyVNYC** [comment]
I am also testing it on lSTM version of Orion-ML and while the time between each file isn't growing as fast as with the Tadgan, it is still growing.  For example, the time between the last few files is about 20 minutes.
Train on 14387 samples, validate on 3597 samples

Here are the times for the last two files. 
This is time 2021-12-16 11:33:08.275011

This is time 2021-12-16 11:53:15.852371

The first two files has these times which are about a little of 2 minutes apart.
This is time 2021-12-14 20:03:53.681484
This is time 2021-12-14 20:06:16.485804

So it also looks like it is happening with the LSTM version also. 

So it maybe when it builds the model every time it fits, it checks its new data against its analysis of the many files before.  So the analysis from before gets larger and larger and it it has to check against more data every time.

**Comment by sarahmish** [comment]
For TadGAN, yes that is the case. We build the model with every `fit` call. You can follow the issue [here](https://github.com/sintel-dev/Orion/issues/261), I will update the code to remove this overhead.

With regards to LSTM, I did not see any problems with the runtime, here is the recorded time from my side

| model | # fit | time (seconds) |
| ------ | ---- | --------------- |
| LSTM |   1    | 76.85                 |
| LSTM |   2    | 77.44                 |
| LSTM |   3    | 77.12                  |
| LSTM |   4    | 76.95                 |
| LSTM |   5    | 78.54                 |

**Comment by sarahmish** [comment]
For TadGAN, yes that is the case. We build the model with every `fit` call. You can follow the issue [here](https://github.com/sintel-dev/Orion/issues/261), I will update the code to remove this overhead.

With regards to LSTM, I did not see any problems with the runtime, here is the recorded time from my side

| model | # fit | time (seconds) |
| ------ | ---- | --------------- |
| LSTM |   1    | 76.85                 |
| LSTM |   2    | 77.44                 |
| LSTM |   3    | 77.12                  |
| LSTM |   4    | 76.95                 |
| LSTM |   5    | 78.54                 |

**Comment by NIckyVNYC** [comment]
Thank you.  That is helpful.
