### ISSUE TITLE
Runtime and sensitivity on performance of TadGAN

### ISSUE THREAD

**Issue by jessb126** [sintel-dev/Orion#263]
Hi @sarahmish
I have some questions related to TadGAN runtime and sensitivity adjustment.

1.Runtime
According to the [published benchmarking leaderboard](https://docs.google.com/spreadsheets/d/1HaYDjY-BEXEObbi65fwG0om5d8kbRarhpK4mvOZVmqU/edit) shared on this Google Doc and my personal experience using orion package and TadGAN pipeline, I found that TadGAN takes a very long to train on CPU machines. According to the results, TadGAN takes around 10k - 20k seconds to finish.
- Is that on 35 epochs mentioned [here](https://github.com/sintel-dev/Orion/blob/master/orion/pipelines/verified/tadgan/tadgan.json) or 2000 epochs declared in the paper? 
- Have you thought about approaches in cutting down the train/detect time? Such as leveraging CudaNN trained on GPU machine etc.

2.sensitivity and global performance
In the paper and repo, I saw that the 4 sigma based fixed thresholding was chosen to be applied to all testing datasets. Have you tried tweaking sensitivity parameter from 4 to other values, and check their respective F1/Precision/Recall and AUC so that global performance can be obtained? If not, could you explain why the static thresholding was chosen?

It will be great if you could clarify those questions to help me understand the package better. Thank you and looking forward to your reply.
Regards

**Comment by sarahmish** [comment]
Hi @jessb126, thanks for opening an issue!

#### 1. Runtime

* **epochs**. The implementation of TadGAN in Orion differs slightly from the model mentioned in the paper. Based on experimentation, we find that 35 epochs is enough to produce an effective result. 
* **gpu**. There is a CudNN version of tadgan which you can find [here](https://github.com/sintel-dev/Orion/blob/master/orion/pipelines/verified/tadgan/tadgan_gpu.json). You can run it by declaring `Orion('tadgan_gpu')`. 

#### 2. Sensitivity

We experimented with different thresholding values, including 3 standard deviations as well as trying a dynamic threshold mechanism, 4 standard deviations away from the mean was the best obtained score, therefore we kept it consistent in our evaluations. 

I hope this answers your questions!

**Comment by NIckyVNYC** [comment]
Question, when I ran 'tadgan_gpu' as the pipeline name instead of just tadgan, I got this error: No module named 'tensorflow.contrib.cudnn_rnn'
I take it I am missing a tensorflow module?

**Comment by sarahmish** [comment]
There is a specific configuration to using tensorflow gpu. Here are some resources to guide you through the setup https://www.tensorflow.org/install/gpu and https://www.tensorflow.org/install/source#gpu. Also keep in mind that TadGAN currently is only supported by tensorflow 1.

**Comment by cjtaylo-csu** [comment]
@NIckyVNYC , I had some issues getting tadgan to run on my GPU as well. This was my resolution:
1. Ensure you have tensorflow 1.14 AND tensorflow-gpu 1.14 installed in your python environment.
2. Make sure you have CUDA 10.0 installed and on your path. This is the version of CUDA that TF 1.14 requires.
