### ISSUE TITLE
Tulog - orion.fit_detect(df) / tgan.fit()

### ISSUE THREAD

**Issue by cjtaylo-csu** [sintel-dev/Orion#264]
* Orion version: 0.2.0
* Python version: 3.7.11
* Operating System: Ubuntu 18.04.5 LTS
* Tensorflow version: 1.15.5

### Description

Tulog fails when running example notebook

### What I Did

`git checkout stable`
`make install`
When running notebook/tulog/Tulog.ipynb with jupyter notebook inside of conda environment, this cell fails:

```
from orion import Orion

orion = Orion(
    pipeline='tadgan.json'
)

anomalies = orion.fit_detect(df)
```

Reported error:

```
ValueError: Error when checking input: expected input_6 to have 3 dimensions, but got array with shape (64, 1)
```
on command `orion.fit_detect(df)`
I checked that tulog.ipynb was freshly checked out on branch *stable*

**Comment by cjtaylo-csu** [comment]
Tulog is broken on *stable* branch.
Works fine on *master*

**Comment by cjtaylo-csu** [comment]
* Orion version: 0.2.0
* Python version: 3.7.11
* Operating System: Ubuntu 18.04.5 LTS
* Tensorflow version: 1.15.5
* Branch: master

### Description

Tulog fails when running example notebook

### What I Did

`git checkout stable`
`make install`
When running notebook/tulog/Tulog.ipynb with jupyter notebook inside of conda environment, this cell fails:

```
from model import hyperparameters
from orion.primitives.tadgan import TadGAN

hyperparameters["epochs"] = 100
hyperparameters["shape"] = (100, 1) # based on the window size
hyperparameters["optimizer"] = "keras.optimizers.Adam"
hyperparameters["learning_rate"] = 0.0005
hyperparameters["latent_dim"] = 20
hyperparameters["batch_size"] = 64

tgan = TadGAN(**hyperparameters)
tgan.fit(X)
```

Reported error:

```
TypeError: fit() missing 1 required positional argument: 'y'
```
on command `tgan.fit(X)`
I checked that tulog.ipynb was freshly checked out on branch *master*

**Comment by cjtaylo-csu** [comment]
Hello,

Thank you for your timely response. 
I still recieve the following error when on branch master and running `make install`:

Cell failing:
```
from model import hyperparameters
from orion.primitives.tadgan import TadGAN

hyperparameters["epochs"] = 100
hyperparameters["shape"] = (100, 1) # based on the window size
hyperparameters["optimizer"] = "keras.optimizers.Adam"
hyperparameters["learning_rate"] = 0.0005
hyperparameters["latent_dim"] = 20
hyperparameters["batch_size"] = 64

tgan = TadGAN(**hyperparameters)
tgan.fit(X)
```

Reported error:

```
TypeError: fit() missing 1 required positional argument: 'y'
```
on command `tgan.fit(X)`

**Comment by sarahmish** [comment]
Hi @cjtaylo-csu, there is still a problem with the installation. Maybe try a fresh environment or reinstalling the entire package.

If you look at the source of `tadgan` on the master branch, you will find that `y` is an optional parameter rather than required (which is the error you are seeing).
https://github.com/sintel-dev/Orion/blob/6548161e240a413ba011a699d109eb8a1e50c148/orion/primitives/tadgan.py#L276

**Comment by cjtaylo-csu** [comment]
I saw that. I then added `tgan.fit(X,X)` like line 285-286 is basically doing:
```
        if y is None:
            y = X.copy()  # reconstruct the same input
```
It was able to run, but the performance of the model was much lower than the outputs in the notebook at fresh clone.

**Comment by sarahmish** [comment]
The performance changes from one run to another, even from my side it wouldn't look exactly like the notebook. This is especially true for TadGAN since it's stochastic.

**Comment by cjtaylo-csu** [comment]
Ok, if the model is making predictions, it may be safe to assume it is working correctly?

Consider using `tf.random.set_seed(seed)` to create repeatable results

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

**Comment by sarahmish** [comment]
Yes exactly, thank you for the suggestion!

**Comment by cjtaylo-csu** [comment]
Ok. Thank you.

I will mark this issue as closed.
