### ISSUE TITLE
multivarite input

### ISSUE THREAD

**Issue by jyoti922** [sintel-dev/Orion#265]
@sarahmish  can u plz provide some example for multivariate data using tadgan at least hoe parameters will change that kind of info should be there...

**Comment by sarahmish** [comment]
Hi @jyoti922, there is a [notebook](https://github.com/sintel-dev/Orion/blob/master/tutorials/Multivariate_Input.ipynb) to help understand how to use multivariate input.

For example if you had a multivariate signal with 25 channels and you want to use `tadgan` specifically, you need to adjust the `input_shape` parameter
```python3
from orion.data import load_signal
from orion import Orion

signal_path = 'multivariate/S-1'
data = load_signal(signal_path)

hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences#1": {
        "window_size": 100,
        "target_column": 0 
    },
    'orion.primitives.tadgan.TadGAN#1': {
        'epochs': 5,
        'verbose': True,
        'input_shape': [100, 25] # where 100 is the window size, and 25 is the number of channels
    }
}

orion = Orion(
    pipeline='tadgan',
    hyperparameters=hyperparameters
)

orion.fit(data)
```

**Comment by jyoti922** [comment]
hi @sarahmish for example we take input shape=[100 , 25] so what will be encoder reshape shape .because for tadgan in case of univariate data ;
encoder_input_shape = (window_size, 1) # (window size,feature)
generator_input_shape = (20, 1)

critic_x_input_shape = (window_size, 1)
critic_z_input_shape = (20,1)

encoder_reshape_shape = (20, 1)
generator_reshape_shape = (window_size//2, 1).

These were the parameters for univariate .so if we take input shape =[100 , 25]   what will be the encoder reshape shape??
because in univariate its (window size, features) which is [100,1] to [20,1 ] 

so what will be for multivariate case [100,25] for TADGAN. and kindly suggest me on which basis (features,or window size) encoder is converting the data into latent space).
kindly suggest me

**Comment by sarahmish** [comment]
Hi @jyoti922, by your example: a single input is of the shape (100, 25) then you get the following:
```
# input dim -> latent dim -> output dim
  (100, 25) ->   (20, 1)  -> (100, 1) 
```

namely what is happening is the encoder encodes that input into its latent representation, in this case `20`, however this is a hyperparameter that you can tweak as well. Then you reconstruct only one dimension of the signal which is indicated by the `target` column in the `mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences`, in the default set up this is the first column in your signal.

```python3
hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences#1": {
        "window_size": 100,
        "target_column": 0 # to change the target channel
    },
    'orion.primitives.tadgan.TadGAN#1': {
        'epochs': 5,
        'verbose': True,
        'input_shape': [100, 25] # to change the number of input channels
        'latent_dim': 20 # to change the dimension of the latent rep
    }
}
```

I have indicated above which hyperparameters you should consider adapting for your data. You will have to experiment and see which values are appropriate. For the `latent_dim` you want to have a concise representation but still large enough to hold information.

Let me know if you have any further questions!

**Comment by Raymondangsetya** [comment]
Hi @sarahmish , following the example being given, I found some errors while fitting the multivariate data (6 column data) to my model. So my input shape is [100,6] and I am expecting output [100,1].  

Orion version: 0.2.0
Python version: 3.6.13
Operating System: Windows 11

Here is my code, 

```
hyperparameters["epochs"] = 40
hyperparameters["input_shape"] = (100, 6) # based on the window size
hyperparameters['target_shape']= (100, 1)
hyperparameters["optimizer"] = "keras.optimizers.Adam"
hyperparameters["learning_rate"] = 0.0025
hyperparameters["latent_dim"] = 20
hyperparameters["batch_size"] = 64
hyperparameters['verbose'] = True
tgan = TadGAN(**hyperparameters)
tgan.fit(X,X)
```

here is the error reported.

`ValueError: Error when checking input: expected input_51 to have shape (100, 1) but got array with shape (100, 6)`

I can't seem to find parameters which need to be change to solve this error. Can you please help me? thanks.

**Comment by sarahmish** [comment]
Hi @Raymondangsetya! Definitely! There is one extra step for multivariate TadGAN if you are running the `tulog.ipynb`, which is that you need to create a `y` variable that refers to the channel you want to reconstruct.

```python3
channel = 0 # index of channel to reconstruct
y = X[:, :, channel:channel+1] # slice it out of X

tgan.fit(X, y)
```

Let me know if you have any further questions!

**Comment by Raymondangsetya** [comment]
Thanks for your reply!!

**Comment by jyoti922** [comment]
hi @Raymondangsetya if you are getting feasible results for multivariate TadGAN kindly help me .I am also using multivariate data i got some results bt i m not sure that they are correct or not.. so kindly help me ..

**Comment by jyoti922** [comment]
@sarahmish can you guide me how to add anomalies within the testing part.as i have trained the normal data accurately  without any fault.now what kind of anomaly should i add for multivariate data .kindly guide me

**Comment by sarahmish** [comment]
Hi @jyoti922! All the pipelines in Orion are _unsupervised_ pipelines, this means that pipelines work on finding anomalous regions without actually looking at ground truth anomalies.

You can test the performance of the pipeline using our [evaluation](https://github.com/sintel-dev/Orion/tree/master/orion/evaluation) metrics. Let me know if you have any further questions

**Comment by NIckyVNYC** [comment]
Hi, I am also interested in using Tadgan for multivariate input.  But say you have 5 signals as the input, can Tadgan or Orion seek to predict more than 1 signal at a time?  The notebook for the mulitvariate gives an example where there is 25 input signals, but then the example predicts anomalies in just 1 signal.  Can it predict multiple signals at the same time?  If not, I was thinking of having my program have several models (4 models) at the same time predicting 4 different signals and then seeing if severity results for the 4 separate signals match using some other python programming.  Nicholas

**Comment by NIckyVNYC** [comment]
Ok, I may have answered my own question, but I am not sure.  I put in the following code and it appears to work as it is training.  So does this mean it will find "severity" based on all 4 signals that it is feeding on?   See the code I used. Specifically for "target_column" i put 4 column values [0, 1, 2, 3].   It appears to be working.

hyperparameters = {
                        "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
                            "interval": 1,

                        },

                        "mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences#1": {
                            "window_size": 100,
                            "target_column": [0, 1, 2, 3]

                        },
                        "orion.primitives.tadgan.TadGAN#1": {
                            'epochs': 3,
                            'verbose': True,
                            'input_shape': [100, 4]

                   }
            }

orion_test = Orion(
    pipeline='tadgan',
    hyperparameters=hyperparameters
    )

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, technically your code works and it should produce what you are looking for! 

Engineering wise, we currently do not explicitly support producing multiple signals yet, it is a future feature to work on. Therefore, I cannot provide much help. For example, if you decide to predict multiple signals at the same time, the error calculation should be more rigorous and considers the case specifically. This is currently unsupported.

**Comment by NIckyVNYC** [comment]
Thank you.  I am continuing to train the model with several signals at the same time.  I will let you know how well it then "detects" the other files.  This is very interesting.

**Comment by NIckyVNYC** [comment]
Sarah, one thing I should point out.  I am training a new model using 4 signals to train it with  3 epochs for each file.  I noted that for training on the same type of files compared to training on 1 signals for 3 epochs the training time for each file has now sped up to 80 seconds from 170 seconds.  The only difference is that 4 signals are being used rather than 1 signal.  The files I am using has something like 15 or more columns.  I may test to see if the time training gets even faster if i use more signals than 4.

**Comment by sarahmish** [comment]
@NIckyVNYC the different between using:
1.  a model for each signal -> total 4 models
2. a model for 4 signals -> total 1 model

is the build time, in case (1) you build the model 4 times, and in case (2) you build it once. Building a model take roughly half a minute which explains the differences you see.

I hope you are enjoying using Orion!

**Comment by jyoti922** [comment]
@sarahmish I have one doubt for encoder and generator dimension.for example you suggested me to use
# input dim -> latent dim -> output dim
  (100, 25) ->   (20, 1)  -> (100, 1) 

but here you are doing the dimension reduction on the basis of window size not on the basis of feature.how can you use   (20 ,1) for latent one because 25 features will be represented by 1 feature .is it feasible??kindly tell me on which basis you are converting original data into latent dimension .why 25->1 feature came why 100-> 20 came .plz clear my doubt for multivariate data

**Comment by jyoti922** [comment]
channel = 0 # index of channel to reconstruct
y = X[:, :, channel:channel+1] # slice it out of X
tgan.fit(X, y)

Hi Sarah ,as u mentioned earlier that for multivariate do  this extra step.But what is the sense of doing this . Coz it's again for a univarite data.
Coz at the end y=X[ : , : ,1]
 so tgan.fit(X,y) 
Simply it will predict new y as  ( : , : , 1) .so again univariate data .apply unroll_ts function converts the data to (;,1) and we got the result.
Kindly suggest a proper way to deal with multivariate data
1.X=(900, 25) 
2.applying window sequence,X=(900,100,25)
3.then for encoder (100,25) as input
4.channel=0
y=X[:,:, channel:channel+1]
5. tgan.fit(X,y)
6. tgan.predict(X,y)
7. So at the end, y will be of shape (900,100,1)
8. so this is not for multivariate. U ll just choose a variable that u want to reconstruct and individually it will work for univariate .it won't be able to capture the correlation among variables.
