### ISSUE TITLE
TadGAN GPU

### ISSUE THREAD

**Issue by cjtaylo-csu** [sintel-dev/Orion#267]
* OS Version: Ubuntu 18.04.5
* Tensorflow/tensorflow-gpu Version: 1.14.0
* Python version: 3.6.13
* Cuda version: 11.5
 
Hello,

What is the correct version of tensorflow/tensorflow-gpu to be used?
I changed the pipeline in the tulog experiment to:

```
orion = Orion(
    pipeline='../../orion/pipelines/verified/tadgan/tadgan_gpu.json'
)
```

But when using tensorflow-gpu 1.14.0 I get the following error:

`DistributionNotFound: The 'tensorflow<2,>=1.11.0' distribution was not found and is required by the application`

The following command sees my GPU:
```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```

Using tensorflow 1.14.0 results in the following error:
`No registered kernels`, and the command above does not see my GPU.

PS: I tried to run in the docker environment but upon running the notebooks/tulog tutorial it crashed saying:

`PermissionError: [Errno 13] Permission denied: '/app/orion/data/'`

Thank you for your help. I am really hoping to use tadgan with my GPU

PS: I posted this comment to Issue #203

**Comment by sarahmish** [comment]
Hi @cjtaylo-csu! In addition to `tensorflow-gpu==1.14` you need to install tensorflow with the same version (`pip install tensorflow==1.14`).

**Comment by cjtaylo-csu** [comment]
Thank you Sarah,

Yes it looks like my CUDA version is incompatible. Is there a list somewhere of tool versions used for orion-ml?

**Comment by cjtaylo-csu** [comment]
Hello, I was able to generate the list I was looking for by running `pip3 list` inside the docker environment.
I also confirmed the tadgan_gpu was working once I had the correct CUDA in place.

Thank you for your help!
