### ISSUE TITLE
TadGAN Runtime

### ISSUE THREAD

**Issue by sarahmish** [sintel-dev/Orion#268]
Dear Sarah, I see you closed this issue and released a new master.   Question, if you remember my problem which was this issue was that I wanted to train Tadgan model on many different files where each file has about 18,000 rows of time stamps and values in the 2nd column.   Before, every time it when to a new file to train epochs after about 100 files, it would take more than 1/2 hour for it to get to the next file, when at the beginning it would just take 6 minutes between the 1st and 2nd file (using a cpu).   And it would exponentially increasing time with each file.  I assume you fixed the problem. Above you say one can either use orion.fit(data) or orion.fit(data, build=True).  I am confused as to which one to use if I want my model to train on thousands of files but not have the training take more time between each file.  Do I use the build=True?  But if I am fitting another model, what does that mean?  If I pick that and train on thousands of different files, will the be thousands of different models?   I assume I pick that so it want continue taking more time increasing between each file?   And also, now that its a master, if I update the orion-ml I assume it will  have that fix, right? . Thanks.  Nicholas.

_Originally posted by @NIckyVNYC in https://github.com/sintel-dev/Orion/issues/261#issuecomment-1028355329_

**Comment by sarahmish** [comment]
@NIckyVNYC – yes! Version 0.2.1 will be released soon and it will solve your issue. 

Note that we made an edit to the original post in #261 and now the `build` parameter is removed. As such, `orion.fit(data)` will continue the training process of the previously built model. 

If you wish to train a new model, you can create a new Orion instance.

I hope this answers your question!

**Comment by NIckyVNYC** [comment]
Dear Sarah, I installed verson0.2.1 into a new Anaconda environment on my Mac to test it.   And I ran the Tadgan pipeline for Version 0..2.1 and I am having the same problem as before.  I want to train my Tadgan model on many files, rather on just one file.  And again, when it trains, it adds more time every time another files is used to train it.  I created a CSV file with timestamps. See attached.   So after a while, it goes from taking 5 minutes for doing 3 epochs to eventually 20 minutes between the 42 and the 43 file.  And it keeps increasing.  Is the Version for 0.2.1 supposed to allow my to train on many separate files without the training time increasing between each additional file?   Am I doing something wrong?  I am just doing orion.fit(data).  
[master_anomaly_list.csv](https://github.com/sintel-dev/Orion/files/8103289/master_anomaly_list.csv)
  

Thank you, Nicholas

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, version 0.2.1 allows you to continue training TadGAN after calling the `fit`, i.e. you can call `fit` many times to train the same model.

I did a quick test from my end by running the following code
```python3
from orion import Orion 
from orion.data import load_signal
import time 

train_data = load_signal('S-1-train')

hyperparameters = { 
    'orion.primitives.tadgan.TadGAN#1': { 
        'epochs': 1, 
        'verbose': True 
    } 
} 
 
orion = Orion( 
    pipeline='tadgan', 
    hyperparameters=hyperparameters 
) 
 
for _ in range(5): 
    start = time.time() 
    orion.fit(train_data) 
    print(time.time() - start) 
```
Runtimes

| model    | # fit |  0.2.1  |  0.2.0   |
| -------- | ---- | ------- | ------ |
| TadGAN |   1    | 56.37   | 49.07  |
| TadGAN |   2    | 18.25   | 71.62   |
| TadGAN |   3    | 17.37   | 102.41 |
| TadGAN |   4    | 17.48   | 125.71 |
| TadGAN |   5    | 18.39   | 152.05|

In version 0.2.1, we stopped rebuilding the model each `fit` call and you can see that it continues the training process.
I'm wondering what reasons might cause the increase of time you are seeing, is the data size increasing as well? It could also be a memory issue.

**Comment by NIckyVNYC** [comment]
Dear Sarah, thank you for your help. I think I solved the problem.  The problem was I was calling the model each time in the for loop going through the files.   For example, 

train_data = load_signal('S-1-train')

for _ in range(5): 

    hyperparameters = { 
        ' orion.primitives.tadgan.TadGAN#1': { 
        'epochs': 1, 
        'verbose': True 
       } 
    } 
 
    orion = Orion( 
        pipeline='tadgan', 
         hyperparameters=hyperparameters 
     ) 
 
    start = time.time() 
    orion.fit(train_data) 
    print(time.time() - start) 

Once I changed it to have to the fit only comes after the for loop than the time is the same for each file.    

Thanks again.
