### ISSUE TITLE
Python 3.8 support?

### ISSUE THREAD

**Issue by NIckyVNYC** [sintel-dev/Orion#282]
Any chance Python 3.8 support coming soon?  Apparently on Macintoshes Tensorflow Metal needs at least Python 3.8.  Given that the new processors on Apple's Macintosh are very powerful it would be great if Orion-ML could take advantage of Tensorflow Metal.   Thanks Nicholas.

**Comment by sarahmish** [comment]
Hi @NIckyVNYC, thank you for opening this issue! 

Definitely! We are actively working on this right now and hopefully we will be able to support python 3.8 very soon!

**Comment by NIckyVNYC** [comment]
Hi Sarah, just following up if a version of Orion-ML that works with python 3.8 will be coming out soon and if not is there a beta version that I could use.  Thanks. Nicholas.
