### ISSUE TITLE
About creating own datasets

### ISSUE THREAD

**Issue by xuchunyu123** [sintel-dev/Orion#294]
* Orion version:0.31
* Python version:3.7
* Operating System:windows10

### Description
Hello, I would like to ask how to create my own dataset, what format should it be, can you give me a sample?

**Comment by xuchunyu123** [comment]
Thank you ,it's helpful.I followed this sample to create my dataset but got another problem:ValueError: Axis 2 is outside the dimensions of X (1).According to the solution of the similar problem I set the hyperparameters but I still have this error, how can I fix it？Here is my dataset and hyperparameter settings.
![image](https://user-images.githubusercontent.com/82310674/170159716-5356f4f6-6572-40eb-a35e-c35aa032f3b5.png)
parameters = {
  'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1': {
    "interval": 0.00001 
  },
  'orion.primitives.tadgan.TadGAN#1': {
    "epochs": 35,
  }
}

**Comment by xuchunyu123** [comment]
There is also the following detailed error message，I would appreciate it if you could give me some guidance.
![sunlogin_20220525154823](https://user-images.githubusercontent.com/82310674/170210510-fe02e388-bbcd-4503-8e6d-ffe892cc6d40.jpg)

**Comment by sarahmish** [comment]
Hi @xuchunyu123 to help debug, which pipeline are you running?
