### ISSUE TITLE
AER model example for multi variate anomaly detection 

### ISSUE THREAD

**Issue by yaseryacoob** [sintel-dev/Orion#296]
@sarahmish @lcwong0928 

I noticed the new AER model added to Orion, and I am trying to use it in multivariate anomaly detection. Looked at https://github.com/sintel-dev/Orion/blob/master/docs/user_guides/primitives_pipelines/primitives/AER.rst and I need a few clarifications

1. I could make X and Y the same, and then the fit would be for the full multivariate signal, in my case something like n*f which seems to compute for https://github.com/sintel-dev/Orion/blob/master/docs/user_guides/primitives_pipelines/primitives/AER.rst. Is this correct?
2. How do I invoke the anomaly detection using AER with a new signal, my new signal is different in length m*f?  (m may be shorter or longer than n).

I tried this, but it is hanging in orion.fit (on your test data), so I maybe setting the primitives wrong.

```
train_data = load_signal('S-1-train')
hyperparameters = {
    'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1': {
        'interval': 1
    }, 
    'orion.primitives.aer.AER#1': {
        'epochs': 5,
        'verbose': True # 
    }
 }

orion = Orion( 
    pipeline='aer',
    hyperparameters=hyperparameters
 )
orion.fit(train_data) 
anomalies = orion.detect(new_data)
print(anomalies)

```

**Comment by sarahmish** [comment]
Hi @yaseryacoob, thank you for your question!

Our assumption is `X` is a multidimensional signal and `y` is one channel of `X` that we wish to reconstruct/detect anomalies in. For the code you have, it is correct! It is just taking very long because you are resampling the signal at `1` interval where the signal actually is at `21600` interval.

If you use the following hyperparameters it should work!
```python3
hyperparameters = {
    'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1': {
        'interval': 21600
    }, 
    'orion.primitives.aer.AER#1': {
        'epochs': 5,
        'verbose': True
    }
 }
```
