### ISSUE TITLE
Running speed drops

### ISSUE THREAD

**Issue by xuchunyu123** [sintel-dev/Orion#299]
### Description
parameters = {
        'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1': {
            "interval": 1
        },
        'orion.primitives.aer.AER#1': {
            "epochs": 35,
            'verbose': True
        },
    }
    orion = Orion(
        pipeline='aer',
        hyperparameters=parameters
    )
    anomalies = orion.fit_detect(df)

### What I Did

I just ran the above code, the speed is very fast in the first 22 epoches, and after a day, the training has no progress. What is the reason, please advise, thank you very much.

**Comment by sarahmish** [comment]
Hi @xuchunyu123! Thank you for using Orion!

I suspect that maybe the memory is overloaded. Can you please share what is the size of your data?
