### ISSUE TITLE
ValueError: Axis 2 is outside the dimensions of X (1).

### ISSUE THREAD

**Issue by ajthomas1949** [sintel-dev/Orion#301]
* Orion version: 0.3.1
* Python version: 3.7.13
* Operating System: Windows 7

### Description

Describe what you were trying to get done.
This is my first attempt to use Orion, which looks great.
Starting with the current CoLab version (https://colab.research.google.com/drive/1TVNK6HroahDeFFl06oOFYISt5JLLSSLO)
I modified the code to load a very simple dataset for testing:

signal = 'foo.csv'
# load signal
df = load_signal(signal)

# load ground truth anomalies NB I don't have any anomaly data, so commented this out
#known_anomalies = load_anomalies(signal)

df.head(20)

timestamp value
1 | 10.0
2 | 11.0
3 | 11.0
4 | 10.0
5 | 11.0
6 | 12.0
7 | 12.0
8 | 13.0
9 | 12.0
10 | 11.0
11 | 10.0
12 | 9.0
13 | 10.0
14 | 10.0
15 | 10.0
16 | 10.0
17 | 10.0
18 | 10.0
19 | 10.0
20 | 10.0

Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.

from orion import Orion
hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        "interval": 1
    },
    "orion.primitives.tadgan.TadGAN#1": {
        'epochs': 5
    }
}

orion = Orion(
    pipeline='tadgan.json',
    hyperparameters=hyperparameters
)
print(df.shape)
anomalies = orion.fit_detect(df)

If there was a crash, please include the traceback here.

Exception caught producing MLBlock orion.primitives.timeseries_preprocessing.slice_array_by_dims#1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mlblocks/mlpipeline.py", line 565, in _produce_block
    block_outputs = block.produce(**produce_args)
  File "/usr/local/lib/python3.7/dist-packages/mlblocks/mlblock.py", line 325, in produce
    return self.primitive(**produce_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/orion/primitives/timeseries_preprocessing.py", line 29, in slice_array_by_dims
    raise ValueError("Axis {} is outside the dimensions of X ({}).".format(axis, dims))
ValueError: Axis 2 is outside the dimensions of X (1).
(25, 2)
```
Thanks for your help!

**Comment by shavidan123** [comment]
Thank you for the detailed description of the issue. How large is the dataset you're using? I've tried replicating your issue and it seems to me that the pipeline works as intended on larger datasets. I tested on a dataframe of random integers with size 1000 and time increasing from 1 to 1000 and it succeeded with no error. When I used the same random dataframe of only size 20, I received the same error log as you. It seems like an error occurs in the aggregation and sequencing step of the pipeline. I'm trying to pinpoint why exactly it is occurring, and I'll bring up this issue in the next dev meeting. Thanks for letting us know! I'll post an update when I'm able to learn more.

**Comment by ajthomas1949** [comment]
hi, Avi,
many thanks for the prompt response. Yes, I used a very small (20 point) data set just to test that everything was working, and got the error described. When I tried to use my actual data set (about 4000 points) everything worked perfectly.
Best regards,
arthur

Arthur J Thomas PhD
CEO
Proteus Associates (Oxford) Ltd
Chipping Campden, UK

**Comment by ajthomas1949** [comment]
hi, I am still getting the error described above with fewer than 100 data points. Is there some
workaround?
Thanks!
