### ISSUE TITLE
About the source of these algorithms

### ISSUE THREAD

**Issue by xuchunyu123** [sintel-dev/Orion#303]
Hello, can you share which paper these anomaly detection algorithms such as dummy, aer, etc. come from? thank you very much

**Comment by sarahmish** [comment]
Hi @xuchunyu123 – thank you for your interest in Orion!

Here is a list of some of the verified pipelines and their sources
| pipeline | source |
| -------- | --------|
| LSTM DT | Hundman et al. (2018), [Detecting Spacecraft Anomalies Using LSTMs and Nonparametric Dynamic Thresholding](https://arxiv.org/abs/1802.04431) |
| LSTM AE | Malhotra et al. (2016), [LSTM-Based Encoder-Decoder for Multi-Sensor Anomaly Detection](https://arxiv.org/abs/1607.00148) |
| ARIMA | Box and Jenkins (1976), Time Series Analysis: Forecasting and Control |
| TadGAN | Geiger et al. (2020), [TadGAN: Time Series Anomaly Detection using Generative Adversarial Networks](https://arxiv.org/abs/2009.07769) |
| MS Azure | Ren et al. (2019), [Time-Series Anomaly Detection Service at Microsoft](https://arxiv.org/abs/1906.03821) |

Some of the in-house algorithms and their papers are still in development.

**Comment by xuchunyu123** [comment]
Very happy to receive your reply, your reply is really helpful, and where is the source of the unverified dummy model?

**Comment by sarahmish** [comment]
The `dummy` pipeline is a simple thresholding method, we mainly use it in the library to test pipelines. It is not based on any paper :)
