### ISSUE TITLE
How to deal with multivarite input??

### ISSUE THREAD

**Issue by jyoti922** [sintel-dev/Orion#311]
channel = 0 # index of channel to reconstruct
y = X[:, :, channel:channel+1] # slice it out of X
tgan.fit(X, y)

Hi Sarah ,as u mentioned earlier that for multivariate do this extra step. But what is the sense of doing this? Coz it's again for a univariate data.
Coz at the end y=X[ : , : ,1]
so tgan.fit(X,y)
Simply it will predict new y as ( : , : , 1) .so again univariate data .apply unroll_ts function converts the data to (;,1) and we got the result.
Kindly suggest a proper way to deal with multivariate data
1.X=(900, 25)
2.applying window sequence,X=(900,100,25)
3.then for encoder (100,25) as input
4.channel=0
y=X[:,:, channel:channel+1]
5. tgan.fit(X,y)
6. tgan.predict(X,y)
7. So at the end, y will be of shape (900,100,1)
8. so this is not for multivariate. U'll just choose a variable that u want to reconstruct, and individually it will work for univariate .it won't be able to capture the correlation among variables.

**Comment by sarahmish** [comment]
Hi @jyoti922, yes you are correct.

Orion only supports taking multivariate as input, however the internal models reconstruct one signal. This is mentioned in the [issue](https://github.com/sintel-dev/Orion/issues/248) related to the new feature.

In the future, we hope to support multivariate output as well.
