### ISSUE TITLE
Installing Orion on Macbook with M2 chip?

### ISSUE THREAD

**Issue by ajthomas1949** [sintel-dev/Orion#316]
* Orion version: current Github version
* Python version: 3.8.9
* Operating System: MacOS 12.56.1

### Description

Trying to install Orion on Macbook with Apple M2 silicon

### What I Did

```
pip3 install orion-ml

ERROR: Cannot install orion-ml and orion-ml==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    orion-ml 0.1.0 depends on mlblocks<0.4 and >=0.3.0
    mlprimitives 0.2.4 depends on mlblocks<0.4 and >=0.3.4
    orion-ml 0.1.0 depends on mlblocks<0.4 and >=0.3.0
    mlprimitives 0.2.3 depends on mlblocks<0.4 and >=0.3.4
    mlprimitives 0.2.2 depends on tensorflow<2 and >=1.11.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts```

**Comment by ajthomas1949** [comment]
Following the suggestion to use a virtual environment in Issue 193 I did 
python3 -m venv orion
source orion/bin/activate
pip3 install orion-ml

I then got:
ERROR: Command errored out with exit status 1:
     command: '/Users/ajt/My Drive/My Projects/Pametan/Technology/Orion/orion/bin/python3' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-1_j46wqg/pandas/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-1_j46wqg/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-nurwyg2c
         cwd: /private/tmp/pip-install-1_j46wqg/pandas/
    Complete output (1377 lines):
    WARNING: The wheel package is not available.
    WARNING: The directory '/Users/ajt/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
      ERROR: Command errored out with exit status 1:
       command: '/Users/ajt/My Drive/My Projects/Pametan/Technology/Orion/orion/bin/python3' '/Users/ajt/My Drive/My Projects/Pametan/Technology/Orion/orion/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py' build_wheel /tmp/tmpoq7pv8ud
           cwd: /private/tmp/pip-wheel-zwbiqcbs/numpy
      Complete output (1338 lines):
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      INFO: blas_opt_info:
and another thousand lines of warnings and INFO messages and finally :
ERROR: Failed building wheel for numpy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/ajt/My Drive/My Projects/Pametan/Technology/Orion/orion/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/ajt/My Drive/My Projects/Pametan/Technology/Orion/orion/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyyu3_1bv', '--quiet', 'numpy>=1.12.0']' returned non-zero exit status 1.

**Comment by sarahmish** [comment]
Hi @ajthomas1949! Thank you for opening this issue.

The main problem here is that you are using python 3.8 while Orion only supports 3.6 and 3.7.

**Comment by ajthomas1949** [comment]
hi, many thanks for your very prompt response! in https://github.com/sintel-dev/Orion/issues/282 you mentioned that
support for 3.8 is coming soon. There is the issue there mentioned with TensorFlow on M2 chips, and also
I gather that there are issues installing numpy and pandas on Apple chips, see https://tilcode.blog/2021/06/14/how-to-install-numpy-and-pandas-for-data-science-in-a-m1-macbook/,, so your installation scripts may need to take account
of those as well. The new MacBooks really scream, so it would be a pity not to be able to use them for Orion!

**Comment by sarahmish** [comment]
Thank you @ajthomas1949!

Definitely! We're still working on adapting the pipelines to work with the new TF
