### ISSUE TITLE
What speedup can be expected from GPUs?

### ISSUE THREAD

**Issue by ajthomas1949** [sintel-dev/Orion#325]
* Orion version: 0.3.3
* Python version: 3.6.15
* Operating System: Linux 4.14.287-215.504.amzn2.x86_64 x86_64

### Description

hi,
I wanted to compare training and anomaly detection times using TadGAN on CPus and GPUs.

### What I Did

```
We created a docker version on an AWS p2.xlarge EC2 instance with 1 NVIDIA K80 GPU. Training and test data
sets had about 9000 data points each. Using 5 epochs, I saw that the training and anomaly detection times 
using the 'tadgan_gpu' pipeline were about 2x faster than usng the regular 'tadgan' pipeline. Is this in line
with experience of others? I was hoping for a greater speed-up!

```

**Comment by sarahmish** [comment]
Hi @ajthomas1949!

From my experience, the GPU counterpart should be faster but this depends also on your hardware. Here's a little experiment I just ran:

```
Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz
NVIDIA TITAN RTX 24 GB
```

|      epochs    |      CPU    |      GPU    |      speedup    |
|-------------|-----------|----------|---------------|
|      5              |      104.2   |      16.2    |      ~6.5x         |
|      10            |      179.2   |      30.7    |      ~5.8x         |
|      20            |     344.8   |      60.5    |      ~5.6x         |
