### ISSUE TITLE
ValueError: Axis 2 is outside the dimensions of X (1)

### ISSUE THREAD

**Issue by ajthomas1949** [sintel-dev/Orion#339]
* Orion version: 0.3.3
* Python version: 3.6.15 with Tesla K80 GPU, CUDA 10.0, CUDnn 7.6.0
* Operating System: AWS Linux 4.14.287-215.504.amzn2.x86_64 x86_64

### Description

As described in [Issue 301](https://github.com/sintel-dev/Orion/issues/301) I'm still getting this error when the data set has fewer than
100 samples. Unfortunately, that's the way my data are. Is there some work-around, or
should I simply accept that TadGAN is not going to work on such short series?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ajthomas1949** [comment]
Many thanks for the prompt response!
The models are trained on a long series (typically 4-5000 samples covering a month's worth of data) 
but the anomaly detection has to be applied to daily data (typically 75-200 samples). Can I 
modify the hyperparameters such as window_size just at detect time, or do I need to train with
a shorter window_size as well?

**Comment by sarahmish** [comment]
I see! In that case, you need to retrain the pipeline. Unfortunately `window_size` is a preprocessing hyperparameter and affects the model training process.
