### ISSUE TITLE
Error on tadgan.score_anomalie

### ISSUE THREAD

**Issue by dxiaosa** [sintel-dev/Orion#354]
* Orion version: the latest version
* Python version: 3.8.13
* Operating System: windows 10

### Description

Hello, I load the dataset 'multivariate/S-1' with 25 features in total to run our tadgan network. Everything looks good in training. However, when calling predict or detect method, the unexpected error occurred in score_anomalies block pasted in following. I have no idea what happen on that. Any suggestion will be helpful, thanks! 

```
Exception caught producing MLBlock orion.primitives.tadgan.score_anomalies#1
Traceback (most recent call last):
  File "D:\Users\j0huan09\miniconda3\envs\orion\lib\site-packages\mlblocks\mlpipeline.py", line 679, in _produce_block
    block_outputs = block.produce(**produce_args)
  File "D:\Users\j0huan09\miniconda3\envs\orion\lib\site-packages\mlblocks\mlblock.py", line 334, in produce
    return self.primitive(**produce_kwargs)
  File "D:\Users\j0huan09\Desktop\TIMExplore\dependencies\tadgans/tadgans\orion\primitives\tadgan.py", line 506, in score_anomalies
    rec_scores, predictions = reconstruction_errors(
  File "D:\Users\j0huan09\Desktop\TIMExplore\dependencies\tadgans/tadgans\orion\primitives\timeseries_errors.py", line 211, in reconstruction_errors
    errors = _dtw_error(true, predictions, score_window)
  File "D:\Users\j0huan09\Desktop\TIMExplore\dependencies\tadgans/tadgans\orion\primitives\timeseries_errors.py", line 129, in _dtw_error
    dist = dtw(true_data, pred_data)
  File "D:\Users\j0huan09\miniconda3\envs\orion\lib\site-packages\pyts\metrics\dtw.py", line 1256, in dtw
    cost_mat = _input_to_cost(x, y, dist, precomputed_cost, region)
  File "D:\Users\j0huan09\miniconda3\envs\orion\lib\site-packages\pyts\metrics\dtw.py", line 86, in _input_to_cost
    cost_mat = check_array(cost_mat, ensure_min_samples=2,
  File "D:\Users\j0huan09\miniconda3\envs\orion\lib\site-packages\sklearn\utils\validation.py", line 918, in check_array
    raise ValueError(
ValueError: Found array with 1 feature(s) (shape=(11, 1)) while a minimum of 2 is required.
```

The code tested is listed here:

```
import numpy as np
from tadgans.orion import Orion
from tadgans.orion.data import load_signal
from model import hyperparameters as networkparams
import modeldef
from tadgans.tutorials.tulog.utils import unroll_multi_ts

signal_path = 'multivariate/S-1'
sliding_win_size = 100
rolling_win_stepsize = 2

rawdata = load_signal(signal_path).iloc[:1000,:3]
rawdata = rawdata.set_index('timestamp')

n_features = rawdata.shape[1]

networkparams = modeldef.set_parameters(
    epochs=1,
    input_shape=(sliding_win_size, n_features),
    target_shape=(sliding_win_size, n_features),
    latent_dim=20,
    batch_size=64,
    optimizer="keras.optimizers.Adam",
)

data = rawdata.reset_index()

hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        "time_column": "timestamp",
        "interval": 1,
        "method": "mean"
    },
    "mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences#1": {
        'target_column': list(range(n_features)),
        'window_size': sliding_win_size,
        'step_size': rolling_win_stepsize,

    },
    "orion.primitives.timeseries_preprocessing.slice_array_by_dims#1": {
        "target_index": list(range(n_features)),
    },
    "orion.primitives.tadgan.TadGAN#1": networkparams,
}

orion = Orion(
    pipeline='tadgan',
    hyperparameters=hyperparameters
)

orion.fit(data)
res = orion.detect(data)
```

**Comment by sarahmish** [comment]
Hi @dxiaosa! Thank you for opening an issue

At the moment `tadgan` does not support multivariate output, because `score_anomalies` is designed for univariate outputs, which is the reason for the error you see here.

Please let me know if you have any further questions!

**Comment by dxiaosa** [comment]
Okay, got it. That means the score_anomalies only works for univariate output which defined by 'target_shape' right? Does it have possibly indirect method to derive the score for each variable, like using a for loop or something? Although seems not easy I think, because the 'target_shape' or 'target_column' have to be determined definitely before the prediction process, emmm..

**Comment by sarahmish** [comment]
There could be an indirect way by altering the `score_anomalies` function to compute the error on each channel, then similarly you would need to alter `find_anomalies` to be applied on each channel and then take the union.

There is also another indirect approach where you can train a model to predict a multivariate output (without the post-processing primitives: `score_anomalies` and `find_anomalies`). Then you can write a for loop on the post-processing primitives. This is not directly supported but you can investigate this [notebook](https://github.com/sintel-dev/Orion/blob/master/tutorials/pipelines/lstm_dynamic_threshold.ipynb) to give you clues on how to approach this.

**Comment by dxiaosa** [comment]
@sarahmish  Okay, got it! Really appreciate !

**Comment by tim-tue** [comment]
Are there any updates on this question raised by [dxiaosa](https://github.com/dxiaosa)? I am very curious about possible ways to  `score_anomalies`  and  `find_anomalies` on multivariate output

**Comment by khadijakhaldi** [comment]
same question, any updates on multivariate output ?
