### ISSUE TITLE
Why smaller batch_size contribute to more computation load?

### ISSUE THREAD

**Issue by dxiaosa** [sintel-dev/Orion#357]
* Orion version: latest version 
* Python version: 3.8.13
* Operating System: window 10

### Description
Hello, I ran tadgans several experiments with supplied tutorials examples on GPU, I found that when batch_size is adjusted bigger, the runtime will be shorter for each epoch. It is controversial to the common sense. And when I decreased the batch_size, It will output 'cuda_error_launch_failed' error. That means smaller batch_size lead to more computation load? I just wonder what is the reason for that. Any advice will be helpful. Thanks.

**Comment by sarahmish** [comment]
Hi @dxiaosa – thank you for opening an issue!

Specifically for `tadgan`, it has a custom training loop which iterates over the samples based on the batch size. I think the inefficiency of the training loop is what causes the runtime to increase. Do you observe the same phenomena with other pipelines?

With respect to the error you get, can you reproduce the problem? I was able to successfully run `tadgan` with `batch_size=1` from my end.

```python3
from orion import Orion

hyperparameters = {
    'orion.primitives.tadgan.TadGAN#1': {
        'epochs': 1,
        'batch_size': 1,
        'verbose': True
    }
}

orion = Orion(
    pipeline='tadgan',
    hyperparameters=hyperparameters
)
```
