### ISSUE TITLE
ValueError: Unknown primitive: mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate

### ISSUE THREAD

**Issue by twotigeres** [sintel-dev/Orion#361]
* Orion version:latest version
* Python version:3.7
* Operating System:Google Colab

### Description

I run the tutorial Tulog.ipynb on Colab, but an error occurs when running pipeline='tadgan.json'.

![image](https://user-images.githubusercontent.com/94185075/202481600-7b3dfc82-7b06-4bfb-87d6-84d1e003dd70.png)

**Comment by sarahmish** [comment]
hi @twotigeres! Thanks for using Orion!

After you finish installing Orion via `pip install orion-ml`, please restart the runtime. From the top bar, click **runtime -> restart runtime**.

Let me know if you have any further questions!

**Comment by AIM-Mathieu** [comment]
> hi @twotigeres! Thanks for using Orion!
> 
> After you finish installing Orion via `pip install orion-ml`, please restart the runtime. From the top bar, click **runtime -> restart runtime**.
> 
> Let me know if you have any further questions!

This worked for me, thanx
