### ISSUE TITLE
different anomaly predictions using the same trained model on the same data - why?

### ISSUE THREAD

**Issue by zeevikal** [sintel-dev/Orion#375]
* Orion version: 0.4
* Python version: 3.6
* Operating System: Linux

### Description
Hi,
I trained tadgan on custom 6-months data. The interval between each data point is an hour, so 3600 is my interval in `time_segments_aggregate` with `window_size` of 100.
When I ran anomaly detection on all 6 months data I got different results than when I ran prediction on all data in "iterations" of every 200 datapoints (hours).
The iterations are implemented by a for loop that runs every 200 hours and performs similar code to a `tulog` notebook.
The difference between 2 prediction approaches can be seen in the figures below:
1. The first figure represents anomaly predictions on whole 6 months data (with static threshold) - a single anomaly event was found.
![image](https://user-images.githubusercontent.com/22215498/212039687-205e9eec-28d4-4b78-aaf6-d26b320cc341.png)
2. While the second figure shows many anomaly events (and different from 1st approach), with same threshold set.
![image](https://user-images.githubusercontent.com/22215498/212040339-4b5b2631-1ecd-4400-bf08-6bbd1755dfa5.png)

Hyperparameters i used:
```
hyperparameters["epochs"] = 10 # 5
hyperparameters["input_shape"] = (100, 1) # based on the window size
hyperparameters["optimizer"] = "keras.optimizers.Adam"
hyperparameters["learning_rate"] = 0.0005
hyperparameters["latent_dim"] = 20
hyperparameters["batch_size"] = 64
```

Error plot of the raw data and the trained model:
![image](https://user-images.githubusercontent.com/22215498/212040662-dcf9a97e-aa84-4532-ae6f-71fc712c548d.png)

### What I Did

Anomaly scoring was done by: `score_anomalies(X, X_hat, critic, X_index, rec_error_type="dtw", comb="mult")` while in 1st approach - X contains whole 6 months data and in the 2nd approach X is 200 datapoints (hours) array, that was created using:
```
for i in range(len(df)):
    tmpdf = df[i:i+200] # iterate every 200 datapoints (hours)
    X, index = time_segments_aggregate(tmpdf, interval=3600, time_column='timestamp')
    X = imp.fit_transform(X)
    X = scaler.fit_transform(X)
    X, y, X_index, y_index = rolling_window_sequences(X, index, 
                                                      window_size=100, 
                                                      target_size=1, 
                                                      step_size=1,
                                                      target_column=0)
```

My Question is - why the predictions are different? while using the same model, the same data, the same functions and hyperparams.
Thanks in advance!

**Comment by sarahmish** [comment]
Hi @zeevikal – thank you for using Orion and the thorough explanation!

What's happening is very reasonable, let me try to answer in detail. The postprocessing primitives `score_anomalies` and `find_anomalies` work with global and local vision. If you restrict it to chopped data (second approach), you will get a different behavior because it doesn't have the global view. 

For example, the `find_anomalies` primitive contains a specific pruning method that discards anomalies if the their severity score is very small compared to the next highest score. In other words, with your data, the first plot possibly pruned all the rest because there is a clear anomaly with a very high severity, while in the second, it does not have access to see the severity of that anomaly specifically.

Though I do want to emphasize that `tadgan` specifically is stochastic and doesn't generate the same output in every run.

Let me know if this answers your question!

**Comment by zeevikal** [comment]
@sarahmish Thank you for the detailed answer!

My intuition suggests that if the same model receives a time segment of the size one is accustomed to seeing (and especially one it seen during training), it should make a forecast that is approximately similar. Am I wrong?

Also, What should I do in order to reduce the variation in predication between the 2 methods?

**Comment by sarahmish** [comment]
Your intuition is correct, `tadgan` is a reconstruction based model and the model should behave similarly in both approaches. The part that's making it different is the postprocessing primitives.

You can change the hyperparameters and see if it reduces these variations, you can check the definition of the postprocessing primitives used [here](https://sintel.dev/Orion/user_guides/primitives_pipelines/primitives.html#postprocessing). I imagine the following settings will help
```python3
hyperparameters = {
    "orion.primitives.timeseries_anomalies.find_anomalies#1": {
        "window_size"=200, # based on the size of the datapoints
        "window_step_size"=10, 
        "min_percent": 0,
        "fixed_threshold": True
    }
}
```

However, this still won't guarantee 100% match.

If consistency is important to you, I would suggest possibly dropping the postprocessing primitives and creating your own, such as a static threshold (shown in the tulog).
