### ISSUE TITLE
Can TadGAN model already be re-used?

### ISSUE THREAD

**Issue by tim-tue** [sintel-dev/Orion#386]
I tried to re-train it on other datasets by after .fit() a model do it again on a new dataset.
to be clear, i **did not save the model in between**. I re-trained it during the same run.

I then saved the model according to https://github.com/sintel-dev/Orion/issues/206#issuecomment-793091041

I however get this error when I in the end save the model and try to load it again for making predictions:

_"WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually."_

what went wrong?

**Comment by sarahmish** [comment]
Hi @tim-tue, thank you for using Orion!

TadGAN can be used for **_prediction only_** after saving the model, it cannot be trained after saving it and loading it. That is why you see the warning signs after loading. It just mentions that there is no configuration for training, which is expected.

I hope this answers your question, let me know if you have further inquires!

**Comment by tim-tue** [comment]
Thank you!
