### ISSUE TITLE
Installing error in Databricks notebook

### ISSUE THREAD

**Issue by ali-Eskandarian** [sintel-dev/Orion#388]
I used !pip install orion-ml to install the package but the error below appeared.

Using cached mongoengine-0.16.3.tar.gz (149 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in mongoengine setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by sarahmish** [comment]
Hi @ali-Eskandarian, thank you for using Orion!

Can you provide more detail on what python version you are using? In addition, can you specify to install the latest version `pip install orion-ml==0.4.1`

Normally we recommend using an independent environment to not have conflicts with other packages.

**Comment by ali-Eskandarian** [comment]
in Databricks notebook (https://community.cloud.databricks.com/), my Runtime is 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12) which has python 3.9 
when I run the code `pip install orion-ml==0.4.1` it says:
ERROR: Could not find a version that satisfies the requirement orion-ml==0.4.1 (from versions: 0.1.0.dev0, 0.1.0)
ERROR: No matching distribution found for orion-ml==0.4.1
but if I use Runtime 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12) which has  python 3.7 then run
`pip install mongoengine `
`!sudo pip install setuptools==57.5.0`
`!pip install mlblocks==0.3.4`
`!pip install orion-ml==0.4.1`
it will be ok but orion.analysis doesn't work, error = 
ContextualVersionConflict: (numpy 1.18.1 (/databricks/python3/lib/python3.7/site-packages), Requirement.parse('numpy~=1.19.2'), {'tensorflow'})
I want to first install it on python 3.9 if it's possible otherwise somehow solve the error in python 3.7

**Comment by sarahmish** [comment]
At the moment, we support python 3.6, 3.7, and 3.8.

I'm curious as to why you are not able to install orion-ml version 0.4.1 directly (note that it does not need `mongoengine`)

**Comment by ali-Eskandarian** [comment]
tnx 
I used py3.8 and it works 
but still, I have an error when I want to run (https://github.com/sintel-dev/Orion/blob/master/tutorials/pipelines/lstm_dynamic_threshold.ipynb)
in code: 
`step = 4

context = pipeline.fit(**context, output_=step, start_=step)
context.keys()`

I got this
NotImplementedError: Cannot convert a symbolic Tensor (lstm_2/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by sarahmish** [comment]
I have seen this error before. I think the numpy version might be out of range.

It should be `numpy>=1.17.4,<1.19`

**Comment by ali-Eskandarian** [comment]
I changed my numpy version to 1.17.4 and 1.18.1 and both lead to the same error:

NotImplementedError: Cannot convert a symbolic Tensor (encoder/bidirectional_1/forward_lstm_2/strided_slice_1:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by sarahmish** [comment]
@ali-Eskandarian would you be able to help me reproduce your error?

I created a databricks notebook with 9.1 LTS runtime version (python 3.8) and the code runs as expected.

<img width="980" alt="Screen Shot 2023-03-09 at 11 26 38 AM" src="https://user-images.githubusercontent.com/40212131/224088017-d38520dc-4693-43bf-be76-979d18bd5cbd.png">
