### ISSUE TITLE
stream data

### ISSUE THREAD

**Issue by ali-Eskandarian** [sintel-dev/Orion#391]
Does this package support streaming data in anomaly detection?

**Comment by sarahmish** [comment]
Hi @ali-Eskandarian – thank you for using Orion!

Can you elaborate more on your requirements? 
At the moment, to call `detect` method, the number of data points needs to be at least equal to the window size setting.

**Comment by ali-Eskandarian** [comment]
Sure, Do you mean the window can roll with stream data? Do you know if the package is suitable for batch data? 
I have a data stream and want to find an anomaly as soon as it appears.

**Comment by sarahmish** [comment]
Yeah exactly, running inference should not be a problem. Orion is suitable for batch data as well.

**Comment by ali-Eskandarian** [comment]
Thanks for ur help.
