### ISSUE TITLE
Typo in xlsxwriter dependency specification

### ISSUE THREAD

**Issue by Dris101** [sintel-dev/Orion#394]
* Orion version: 0.4.2.dev0

Should be
```
'xlsxwriter>=1.3.6,<1.4',
```
Rather than (comma missing)
```
'xlsxwriter>=1.3.6<1.4',
```

https://github.com/sintel-dev/Orion/blob/676f62fcd8abb3f1af2f84d6770a764f3965f7d5/setup.py#L32

Currently throws error when first instantiating ```Orion``` class
```
InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    xlsxwriter (>=1.3.6<1.4)
               ~~~~~~~~^
```

**Comment by sarahmish** [comment]
Thank you @Dris101 for pointing this issue!
