### ISSUE TITLE
tadgan tutorial not working

### ISSUE THREAD

**Issue by rishishr** [sintel-dev/Orion#406]
* Orion version:
* Python version:3.7
* Operating System: colab

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

<img width="566" alt="Screenshot 2023-04-06 223118" src="https://user-images.githubusercontent.com/82063515/230446530-e3f709fe-2c02-43bc-a0c3-9761b3e97f4a.png">
<img width="485" alt="Screenshot 2023-04-06 223036" src="https://user-images.githubusercontent.com/82063515/230446537-d3183133-0e45-4ae7-8ffb-12eae004a047.png">

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: urllib3<1.26,>=1.25.4 in /usr/local/lib/python3.9/dist-packages (1.25.11)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting orion-ml
  Using cached orion_ml-0.1.0-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: tabulate<0.9,>=0.8.3 in /usr/local/lib/python3.9/dist-packages (from orion-ml) (0.8.10)
Collecting pandas<0.25,>=0.23.4
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-bfad54a8a5f0>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from orion.data import load_signal
      2 
      3 train_data = load_signal('S-1-train')
      4 train_data.head()

ModuleNotFoundError: No module named 'orion.data

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

!pip install 'urllib3>=1.25.4,<1.26'
%pip install orion-ml #'urllib3>=1.25.4,<1.26'
```

**Comment by sarahmish** [comment]
Hi @rishishr -  thank you for pointing this issue!

There is a current problem that we only support `python 3.6, 3.7, and 3.8` and recently colab has upgraded to `python 3.9`. We need to downgrade python version in colab for the tutorial to work.

**Comment by sarahmish** [comment]
Hi @rishishr, I updated the tulog to download python 3.8

It's a workaround for now. Hope this helps!

**Comment by rishishr** [comment]
Sure,
Thank you

**Comment by rishishr** [comment]
There is still error for installing orion...
