### ISSUE TITLE
TadGan paper epoch number and verified pipeline discrepancy

### ISSUE THREAD

**Issue by SebiChesh** [sintel-dev/Orion#411]
Hi there Im looking to recreate the results from the TadGan paper, but I see in your verified pipelines you have epochs set at 70 for MSL and SMAP whist in the paper the author states 2000 "iterations" (2000 iterations I'm assuming is equivalent to 2000 epochs). I was wandering if there is a reason behind the difference, or am I misinterpreting something. Thank you for your help and your work is amazing.

![image](https://user-images.githubusercontent.com/67597947/233601232-db927655-b01d-4175-b05b-491cd62c9621.png)
![image](https://user-images.githubusercontent.com/67597947/233601790-1e27b2e1-24a9-4a95-ba27-da9a383133da.png)

**Comment by sarahmish** [comment]
Hi @SebiChesh, this is very good question!

In the previous tadgan implementation, the number of training steps was 2000. However, it was not exactly equivalent to the number of iterations over the entire dataset. After refactoring tadgan, 2000 was approximated to 70 epochs.
