### ISSUE TITLE
WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria

### ISSUE THREAD

**Issue by mohammadx0098** [sintel-dev/Orion#416]
* Orion version: 0.4.1
* Python version: 3.8
* Operating System: windows

I hope this message finds you well. I am currently using the orion-ml package with a GPU in my Python project and have come across an issue with a warning message that reads:

`**WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU.**`

I am reaching out to you because I am not sure what this warning message means, and I am concerned that it may affect my project. I would be grateful if you could provide some insight into this issue and any potential solutions.

Thank you very much for your time and assistance.

**Comment by sarahmish** [comment]
Hi @mohammadx0098, thank you for using Orion!

The warning is only suggesting that the cuDDN kernel is not being used.
If you're using `tadgan` pipeline and would like to use GPU, please use `tadgan_without_dropout_gpu`.
