### ISSUE TITLE
Using pipelines with GPU after TF2.0

### ISSUE THREAD

**Issue by nunobv** [sintel-dev/Orion#417]
* Orion version: 0.4.1
* Python version: 3.8.10
* Operating System: Windows 10

**Libraries**
* tensorflow==2.3.4
* tensorflow-gpu==2.3.4
* CUDA==10.1
* cuDNN==7.6

### Description

After the migration to TF2.0, how can i run the verified pipelines using GPU?
If I call the standard TadGAN pipeline using `tadgan.json` i get the same message as reported in #416.

Furthermore, I don't seem to find the previous `tadgan_gpu.json` pipeline which is mentioned in older posts/issues.

I have a NVIDIA GeForce RTX 3060 Ti, which barely goes higher than 6%-8% in utilization, leading me to believe that the GPU is barely being utilized, if being used at all.

Any help appreciated.

**Comment by sarahmish** [comment]
Hi @nunobv, thank you for opening this issue!

In TF 2.0 most pipelines use GPU by default if available. For tadgan specifically, please use `tadgan_without_dropout_gpu` which satisfies the cuDDN criteria.

Please let me know if you have any further questions

**Comment by nunobv** [comment]
Thank you for your always quick responses @sarahmish.

I tried your suggestion, but there is no time difference using `tadgan_without_dropout_gpu` and the standard `tadgan` pipelines. I tried for different epochs and the elapsed time is pretty much the same (and in some cases higher for the former).

Furthermore, I understand that `tadgan_without_dropout_gpu` has a different architecture than `tadgan`, am I right?

**Comment by sarahmish** [comment]
The expectation of `tadgan_without_dropout_gpu` is to use `cuDNN kernel` in LSTM layers since the `recurrent_dropout` parameter is set to zero, rather than falling back on a generic kernel.

Do you still observe that warning that tensorflow is using a generic kernel?

**Comment by nunobv** [comment]
No, the `tadgan_without_dropout_gpu` pipeline does not show the warning.

However, it apparently also fails to "improve" the speed when using GPU vs CPU (which I was expecting). I'll try to do some more testing, as I cannot explain this behavior.

**Comment by sarahmish** [comment]
@nunobv here is a result of my experiment on the `S-1` dataset and `tadgan` pipeline with NVIDIA TITAN RTX in gpu mode.

| epochs | CPU    | GPU   |
|--------|--------|-------|
| 5      | 74.76  | 36.75 |
| 10     | 132.00 | 54.84 |
| 20     | 248.81 | 93.16 |

With more epochs and larger datasets CPU doesn't scale well.

**Comment by nunobv** [comment]
Thank you @sarahmish.

Indeed I confirm the same pattern in my machine (although a bit slower when compared to yours!).
Thank you for your patience.
