### ISSUE TITLE
installtion error and python version depedencies 

### ISSUE THREAD

**Issue by Abloxo1** [sintel-dev/Orion#423]
* Orion version:0.5.1.dev0
* Python version:3.8t.0
* Operating System:linux, ubuntu 

### Description

Describe what you were trying to get done.
i am trying to install orion 

Tell us what happened, what went wrong, and what you expected to happen.
it is not compatible with 3.8 packages , always given me different errors regarding the version of the package, of my python for example :
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    numpy (>=1.15.4scipy>=1.3.0scikit-learn>=0.20.4joblib>=0.12numba>=0.45.1)

### What I Did
i changed the version of my python to 3.8.0
i tried to modify the setup.py to this :
setup(
    ...
    install_requires=[
        'numpy>=1.15.4', 
        'scipy>=1.3.0', 
        'scikit-learn>=0.20.4', 
        'joblib>=0.12', 
        'numba>=0.45.1'
    ],
    ...
)
 
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by sarahmish** [comment]
Hi @Abloxo1 – thank you for using Orion!

Can you describe what method you used for installation?

I recommend creating a new environment to not clash with other packages
```bash
conda create --name orion-env python=3.8
conda activate orion-env

pip install orion-ml
```

**Comment by Abloxo1** [comment]
Dear Mrs Sarah Alnegheimish

 i have tried your suggestion and  i am acutaly using ubuntu , i tried creating another environment and i tried it to install python 3.6 , 3.7, 3.8, to  fix the dependencies issue but it is still the same , i am not sure how can i solve it "
regards
________________________________

**Comment by sarahmish** [comment]
Hi @Abloxo1, can you please show the entire trace when you are trying to install orion via `pip install orion-ml`?
The error mentioned above might arise when pip is is not updated. Can you please try to upgrade pip as well using `pip install --upgrade pip`?

Sorry I can't tell much from the error above.

**Comment by Abloxo1** [comment]
Dear sarah,

here is the steps i tried first it is
after i installed 3.8.0 python version
and then i tried to install it again and to [cid:65dbc835-0c3a-4e84-a173-91d5cc8f3923] [cid:1322ea06-e5d3-4b2e-a888-8ec2f77f9a58] over come  , then it was successfully been installed but i always get dependencies issue that are include it in the configuration of orion
i have included the pictures

________________________________

**Comment by Abloxo1** [comment]
Dear Mrs,Sarah Alnegheimish,

i am using my virtual environment ubuntu ,After trying the proposed solutions, I have not been successful in downloading the package,
what is the possible way to fix this issue ?,

sincerely,
________________________________

**Comment by sarahmish** [comment]
Hi @Abloxo1, can you attach a screenshot of the error message you are receiving?

**Comment by Abloxo1** [comment]
Dear Sarah ,

after configuring the python version to 3.8 , there always a conflict dependency between the libraries specially NumPy. as you can see  in the image.

hopefully you can help me to solve this issue.
sincerely
________________________________

**Comment by sarahmish** [comment]
Hi @Abloxo1, sorry I have not seen this reply. I do not see the image.

Please open a new issue with the conflicts you are having.
