### ISSUE TITLE
Trying to run orion on personal dataset - KeyError: 'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1'```

### ISSUE THREAD

**Issue by ushasai** [sintel-dev/Orion#426]
* Orion version:
* Python version:
* Operating System:

### Description
Hi! #424 

I have been trying to run Orion on my personal dataset to understand the anomalies in traffic flow dataset. The dataset looks like:

timestamp	value
0	1546300800	90
1	1546301100	65
2	1546301400	68
3	1546301700	95
4	1546302000	114

But while I was trying to run TADGAN, it's giving me the below error:
KeyError: 'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1'```

### What I Did
I even changed the interval as you suggested in other posts, to 300 based on my dataset.
I initially cloned Orion from the GitHub repo, and later I installed it using pip. In either case, the issue still persists. 

hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        'interval': 300,
    },
    'orion.primitives.tadgan.TadGAN#1': {
        'epochs': 5,
        'verbose': True,
    }
}

orion = Orion(
    pipeline='tadgan',
    hyperparameters=hyperparameters
)

Please let me know what I am doing wrong. Kindly help me out.

Thanks in Advance:)
```
Paste the command(s) you ran and the output.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_6960\3650299865.py in <module>
      1 orion = Orion(
      2     pipeline='tadgan',
----> 3     hyperparameters=hyperparameters
      4 )

~\anaconda3\envs\tad\lib\site-packages\orion\core.py in __init__(self, pipeline, hyperparameters)
     62         self._pipeline = pipeline or self.DEFAULT_PIPELINE
     63         self._hyperparameters = hyperparameters
---> 64         self._mlpipeline = self._get_mlpipeline()
     65         self._fitted = False
     66 

~\anaconda3\envs\tad\lib\site-packages\orion\core.py in _get_mlpipeline(self)
     54         mlpipeline = MLPipeline(pipeline)
     55         if self._hyperparameters:
---> 56             mlpipeline.set_hyperparameters(self._hyperparameters)
     57 
     58         return mlpipeline

~\anaconda3\envs\tad\lib\site-packages\mlblocks\mlpipeline.py in set_hyperparameters(self, hyperparameters)
    562         hyperparameters = self._sanitize(hyperparameters)
    563         for block_name, block_hyperparams in hyperparameters.items():
--> 564             self.blocks[block_name].set_hyperparameters(block_hyperparams)
    565 
    566     def _get_block_args(self, block_name, block_args, context):

KeyError: 'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1'```

**Comment by nunobv** [comment]
Hi @ushasai.
Without knowing your Orion version, it's difficult to give you a better answer. But reading through your error, I believe it's because Orion has migrated from MLPrimitives to MLStars.

The hyperparameter specification should change to:
`mlstars.custom.timeseries_preprocessing.time_segments_aggregate#1` 

The verified pipelines have all been updated. You're probably using an older version.
Hope this helps.

**Comment by sarahmish** [comment]
Hi @ushasai – thanks for using Orion!

Yep, exactly as @nunobv just mentioned! In version 0.5.0 we upgraded from `mlprimitives` to `mlstars` and you will need to edit the name of the primitive above

**Comment by ushasai** [comment]
Thank you so much @nunobv and @sarahmish, for your prompt responses. It helped. I just have one more question, can you please suggest some ways to improve the model's performance on my dataset? My F1 score is pretty bad. kindly let me know. Thank you once again:)

**Comment by sarahmish** [comment]
@ushasai, I recommend trying different window sizes and focus on the post processing primitives.

It's hard to point out how to improve the pipeline blindly. I recommend plotting the signal and results and see what aspects they are missing in order to improve the pipeline.
