### ISSUE TITLE
IndexError with very simple dataset when replicating CSV_Analysis_Example.ipynb

### ISSUE THREAD

**Issue by SewoongLee** [sintel-dev/Orion#428]
* Orion version: v0.5.0 - 2023-05-23 [Latest](https://github.com/sintel-dev/Orion/releases/latest)
* Python version: 3.6.8
* Operating System: Windows

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I am trying to apply models in orion with very simple data.
I made an sin wave data, according to the format of [CSV_Analysis_Example.ipynb](https://github.com/sintel-dev/Orion/blob/master/tutorials/CSV_Analysis_Example.ipynb),
but there was IndexError.
Could you tell me what is wrong with my usage?

### What I Did

[This ](https://github.com/sintel-dev/Orion/files/11883227/Untitled.zip) is the zip file of jupyter notebook (ipynb).

This is the py code.
```
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import logging;

logging.basicConfig(level=logging.ERROR)
logging.getLogger().setLevel(level=logging.ERROR)

import warnings
warnings.simplefilter("ignore")


# In[2]:


from orion.data import load_signal

# signal_path = 'S-1'

# data = load_signal(signal_path)
# data.head()


# In[3]:


import numpy as np
import matplotlib.pyplot as plt
value = np.sin(np.linspace(start=0, stop=10, num=100))
plt.plot(value)


# In[4]:


import pandas as pd
df = pd.DataFrame({
    "timestamp": range(100,200),
    "value": value
})
df


# In[5]:


from orion.analysis import analyze

hyperparameters = {
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

pipeline = 'lstm_dynamic_threshold'

anomalies = analyze(pipeline, df, hyperparams=hyperparameters)
anomalies


```

This is the screenshot.
![image](https://github.com/sintel-dev/Orion/assets/7731970/3a9d31b2-7f57-45fd-b586-43fa9a148764)

Thanks in advance!

**Comment by sarahmish** [comment]
Hi @SewoongLee, thank you for using Orion!

The problem here is that the length of `df` is as short as the `window_size` of the pipeline which is 100.
I recommend to make the data longer or change the settings of the pipeline to have a shorted window size, e.g. 10.

Let me know if you have any further questions!

**Comment by SewoongLee** [comment]
> Hi @SewoongLee, thank you for using Orion!
> 
> The problem here is that the length of `df` is as short as the `window_size` of the pipeline which is 100. I recommend to make the data longer or change the settings of the pipeline to have a shorted window size, e.g. 10.
> 
> Let me know if you have any further questions!

Thank you very much, @sarahmish !

**Comment by SewoongLee** [comment]
I tried @sarahmish 's solution today. 
I am afraid it's still not working even though I used longer DataFrame length.
There is same error.

Here is screenshot,
![screencapture-localhost-8888-notebooks-Untitled-ipynb-2023-07-05-22_03_54](https://github.com/sintel-dev/Orion/assets/7731970/02bc7bee-fbe4-4891-8817-d32a9b82d19e)

here is python code,
`#!/usr/bin/env python
# coding: utf-8

# In[1]:


import logging;

logging.basicConfig(level=logging.ERROR)
logging.getLogger().setLevel(level=logging.ERROR)

import warnings
warnings.simplefilter("ignore")


# In[2]:


from orion.data import load_signal

# signal_path = 'S-1'

# data = load_signal(signal_path)
# data.head()


# In[3]:


import numpy as np
import matplotlib.pyplot as plt
value = np.sin(np.linspace(start=0, stop=100, num=1000))
plt.plot(value)


# In[4]:


timestamp = np.array(range(1000))


# In[5]:


import pandas as pd
df = pd.DataFrame({
    "timestamp": timestamp,
    "value": value
})
df


# In[6]:


from orion.analysis import analyze

hyperparameters = {
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

pipeline = 'lstm_dynamic_threshold'

anomalies = analyze(pipeline, df, hyperparams=hyperparameters)
anomalies

`

, and here is ipynb file.
[Untitled (1).zip](https://github.com/sintel-dev/Orion/files/11958186/Untitled.1.zip)

**Comment by sarahmish** [comment]
Hi @SewoongLee! Yes I forgot to mention that you also need to change the interval setting in `time_segment_aggregate` primitive. Since the gap between each timestamp and another is 1 second (default is 6 hours), `interval=1` will be sufficient.

```
hyperparameters = {
    'mlstars.custom.timeseries_preprocessing.time_segments_aggregate#1': {
        "interval": 1
    },
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}
```

**Comment by SewoongLee** [comment]
> Hi @SewoongLee! Yes I forgot to mention that you also need to change the interval setting in `time_segment_aggregate` primitive. Since the gap between each timestamp and another is 1 second (default is 6 hours), `interval=1` will be sufficient.
> 
> ```
> hyperparameters = {
>     'mlstars.custom.timeseries_preprocessing.time_segments_aggregate#1': {
>         "interval": 1
>     },
>     'keras.Sequential.LSTMTimeSeriesRegressor#1': {
>         'epochs': 5,
>         'verbose': True
>     }
> }
> ```

Thank you very much, @sarahmish ! It works perfectly now. :)
