### ISSUE TITLE
How to see reconstructed time serie?

### ISSUE THREAD

**Issue by mohammadx0098** [sintel-dev/Orion#432]
Hi 

1.
I want to use tadgan_without_gpu_dropout and have the visualized option.

How can I do that?

I am training my model and I think my problem is related to ability of my model to reconstruct the time serie.

2.
When I'm usiing orion-ml in my windows local machine I have problem with mathplotlib and I think it's because of the conflict between your package and matplotlib in numpy or pandas version.

Which version of matplotlib is compatible with your package?

**Comment by mohammadx0098** [comment]
After learning with these hyperparameters , the model  learned the time serie but why th amplitudes are not the same?
![IMG_20230716_001828_850](https://github.com/sintel-dev/Orion/assets/62437179/842db662-3abc-4cce-ae29-d15beb9c02e4)

Not just plot the reconstructed signal :
![Uploading IMG_20230716_001830_530.jpg…]()

**Comment by sarahmish** [comment]
Hi @mohammadx0098, thanks for using Orion!

1. To do that, you need to add a `visualization` option to the pipeline json. please add the following block to the `tadgan_without_gpu_dropout` pipeline after the `output_names` block.
```
"outputs": {
    "default": [
        {
            "name": "events",
            "variable": "orion.primitives.timeseries_anomalies.find_anomalies#1.y"
        }
    ],
    "visualization": [
        {
            "name": "generated_timeseries",
            "variable": "orion.primitives.tadgan.score_anomalies#1.predictions"
        }
    ]
}
```

2. Here is matplotlib version that I use
```
matplotlib==3.5.3
matplotlib-inline==0.1.6
```
you can also let pip resolve this compatibility by installing both packages together using `pip install orion-ml matplotlib`

3. There are extreme values in the original time series that are probably affecting the learning process and shifting your reconstructed time series.

**Comment by mohammadx0098** [comment]
@sarahmish 
Thanks.
1. Why generated_timeseries has morr than 1 result . Which one should I plot to see the reconstructed signal?

3.I train the model witjout extreme values. The shift is solved but I have still have the problem with amplitute of the signal with is not the same as original one.
I will send the results

**Comment by sarahmish** [comment]
Hi @mohammadx0098!

The `generated_timeseries` contains 5 dimensions representing the minimum, 25th, 50th, 75th, and maximum values respectively. To plot the results, I made a quick snippet here to visualize the generated time series

```python3
import matplotlib.pyplot as plt

signal = viz['generated_timeseries']
signal = signal.squeeze(1)

x = len(signal)
median = signal[:, 2]
y1 = signal[:, 1]
y2 = signal[:, 3]

plt.plot(median)
plt.fill_between(range(x), y1, y2, alpha=0.3)
plt.show()
```
