### ISSUE TITLE
Fail to downgrade to python 3.8 when I tryed to run the tutorial

### ISSUE THREAD

**Issue by YuanZi1501040205** [sintel-dev/Orion#435]
* Orion version: [0.5.1.dev0](https://github.com/sintel-dev/Orion/commit/4d717501cbf8a0d7097929be622bd69fa8250823)
* Python version: colab default: Python 3.10.6
* Operating System: Colab runtime, T4, standard

### Description

I am trying to run the tutorial Tulog.ipynb but failed to downgrade the python version from 3.10 to 3.8

# install pip for new python
!sudo apt-get install python3.8 python3.8-dev python3.8-distutils libpython3.8-dev
!sudo update-alternatives --config python3
!wget https://bootstrap.pypa.io/get-pip.py
!python get-pip.py

# install colab's dependencies
!python -m pip install ipython ipython_genutils ipykernel jupyter_console prompt_toolkit httplib2 astor importlib-metadata
import sys

sys.path.append("/usr/lib/python3.8")
sys.path.append("/usr/local/lib/python3.8/")
sys.path.append("/usr/local/lib/python3.8/dist-packages")

# check python version
! python --version # should be 3.8.10

Python 3.10.6

Can you update this part of code to allow us at least to reproduce the results you are showing?

Many thanks!

**Comment by sarahmish** [comment]
Hi @YuanZi1501040205 – thanks for using Orion!

Since this is a replication of your question on slack, I will go ahead and close it.

Feel free to reopen the issue if you are still facing issues!
