### ISSUE TITLE
multivariate output 

### ISSUE THREAD

**Issue by khadijakhaldi** [sintel-dev/Orion#438]
1. I have a time series data of 4 sensors, an anomaly happens if one or two sensors have a peak value. If all of them have a peak at the same timestamp it is not an anomaly. As far as I know your models detect an anomaly in only one column. Is that correct ?

2. If it is the case, does it make sense to run the model 4 times on each of my sensors data columns? because in my case an anomaly depends on all the 4 sensors values at the same timestamp.
Thanks in advance!

**Comment by sarahmish** [comment]
Hi @khadijakhaldi – thank you for using Orion!

1. yes, all currently available pipelines detect anomalies in only one column.
2. It definitely does. I recommend that you use all 4 sensors as input the pipeline. However, you alter the target column in each time you run the pipeline. 

Hope this helps, let me know if you have any further questions!
