### ISSUE TITLE
cannot import name 'Orion' from 'orion' 

### ISSUE THREAD

**Issue by cavaglia** [sintel-dev/Orion#461]
* Orion version: 0.5.1 (current)
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

I'm following your quickstart: https://github.com/sintel-dev/orion

Install is OK, but the example fails with this traceback error at the line 

-------------------------------------------------------------
from orion import Orion

ImportError                               Traceback (most recent call last)
Cell In[7], line 1
----> 1 from orion import Orion
      3 hyperparameters = {
      4     'orion.primitives.aer.AER#1': {
      5         'epochs': 5,
      6         'verbose': True
      7     }
      8 }
     10 orion = Orion(
     11     pipeline='aer',
     12     hyperparameters=hyperparameters
     13 )

ImportError: cannot import name 'Orion' from 'orion' (/home/userx/Research/Orion/orion/lib/python3.8/site-packages/orion/__init__.py)

-----------------------------------
Thanks!

**Comment by sarahmish** [comment]
Hi @cavaglia, thank you for using Orion!

It seems like it cannot detect the orion package. 
In the same cell can you please run `! pip freeze | grep orion-ml` to confirm that the package is visible to the environment?

**Comment by cavaglia** [comment]
Hi @sarahmish . I think it was a conflicting problem. So I reinstalled everything on a separate environment. I still see some conflicts but now it runs. Are you still interested to the pip freeze to see the conflicts? Thanks for your prompt reply!

**Comment by sarahmish** [comment]
Nice! I typically recommend creating a virtual environment to remove any potential package conflicts.

**Comment by sarahmish** [comment]
Closing this now, please reopen if you have more question!
