### ISSUE TITLE
ValueError: Unknown primitive: mlstars.custom.timeseries_preprocessing.time_segments_aggregate

### ISSUE THREAD

**Issue by potatoVStomato** [sintel-dev/Orion#482]
* Orion version:0.2.7
* Python version:3.8
* Operating System:windows

###Description:
The location where running Tulog.ipynb gives an error is as follows:
from orion.core import Orion
orion = Orion(
    pipeline='tadgan.json'
)
anomalies = orion.fit_detect(df)
###ValueError: Unknown primitive: mlstars.custom.timeseries_preprocessing.time_segments_aggregate
Note: I have installed orion-ml 0.5.2.dev0

Dear author, what can I do to solve this problem?

**Comment by sarahmish** [comment]
Hi @potatoVStomato, thank you for using Orion!

I have noted your issue and made some changes to the tulog, please try it again now and make sure to run the fourth cell that calls `add_primitives_path` and `add_pipelines_path`.
This should fix the above error.

If you are still facing issues, please let me know!

**Comment by dxiaosa** [comment]
> Hi @potatoVStomato, thank you for using Orion!
> 
> I have noted your issue and made some changes to the tulog, please try it again now and make sure to run the fourth cell that calls `add_primitives_path` and `add_pipelines_path`. This should fix the above error.
> 
> If you are still facing issues, please let me know!

Same problem. seems didn't find add_primitives_path and add_pipelines_path in tulog. Does it still not been updated yet?

**Comment by sarahmish** [comment]
Make sure you run cell 4 in the tulog, it should fix the issue above.

I recently updated the tulog to install the latest version of Orion from github directly. This makes it compatible with python 3.10 and colab. If you still see the issue above, please let me know!
