### ISSUE TITLE
Facing the issue when fitting the model:  "TypeError: Optimizer.apply_gradients() missing 1 required positional argument: 'grads_and_vars'"

### ISSUE THREAD

**Issue by shimonymittal** [sintel-dev/Orion#500]
I am facing the issue when fitting the model. The model is giving error 

"TypeError: in user code:

    File "/home/ec2-user/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/home/ec2-user/tadGAN_2.py", line 443, in train_step  *
        self.critic_x_optimizer.apply_gradients(zip(critic_x_gradient,self.critic_x.trainable_variables))

    TypeError: Optimizer.apply_gradients() missing 1 required positional argument: 'grads_and_vars'"

I don't understand where is this coming from

**Comment by sarahmish** [comment]
Hi @shimonymittal! Thank you for opening this issue!

Can you provide a bit more detail on your setup? please list `tensorflow` and `keras` versions as well as how you installed Orion and which version it is. In addition, if you can include the script that causes the error above.

I made a colab notebook [here](https://colab.research.google.com/drive/1xOFUQyFP89L6984O-FYObSsRaNFUxoPl?usp=sharing) to try and reproduce the issue but it runs fine on colab!

**Comment by shimonymittal** [comment]
The issue was with the optimizer, I had passed optimizer in the form not optimal to the compile function
