### ISSUE TITLE
Question:  How do I train large online data with Orion?

### ISSUE THREAD

**Issue by nntp4** [sintel-dev/Orion#501]
### Description
I have large Kafka clusters, that produce greater than 10 TB of messages (logging) per-day, in this case, I want to use Orion to detect some metrics. 

Could you give me some advice? THX

**Comment by sarahmish** [comment]
Hi @nntp4 -- thank you for using Orion!

Can you provide more detail on the problem such that I can help you. In total, how many rows are recorded per day? Would it be sufficient if a pipeline is trained on a single day, then we can reuse the pipeline and detect anomalies in the upcoming days? How often are you expecting to find anomalies in your data?

The more details you can provide, we can better craft the problem.

**Comment by nntp4** [comment]
@sarahmish  Thank your replay 
 actually, that is HTTP traffic stored as a logging record in Kafka, My company's HTTP Gateway generates around 6~ billion requests per day, and I am responsible for monitoring network traffic for all HTTP domains. The traffic follows some certain pattern, for example, with particularly high volume during the daytime, especially in the morning work period.  I aim to detect any anomalies in the traffic within 15 minutes, preferably no more than 30 minutes, and to keep control of delays during the detection process.

**Comment by sarahmish** [comment]
Thank you for the details! @nntp4!

For **training**, ideally you would diverse set containing multiple days. Seeing that your data is massive, I would consider approaches to reduce the number of requests, such as aggregating over 1 minute `interval=60`. Depending on your domain knowledge, and how anomalies typically behave, you can choose whether you would like to apply such preprocessing or not.
We only need to train once, therefore, this step will be the most time consuming. Before training on the entire dataset, I recommend training on the first hour and see if it is performing as you'd like.

For **inference**, you'll require to run the detect method every ~15 minutes or so. Moreover, you will need to retrain your pipeline every once in a while (e.g, 4 weeks).

I also want to note that it might be beneficiary to breakdown the problem a bit more. For example, each HTTP domain can be trained separately to capture their patterns more clearly.
