### ISSUE TITLE
CSV Analysis Example with Custom Data

### ISSUE THREAD

**Issue by eliashyatt** [sintel-dev/Orion#504]
* Orion version: 0.5.1
* Python version: 3.8.18
* Operating System: Windows 10

### Description

I tried running the code in [CSV Analysis Example](https://github.com/sintel-dev/Orion/blob/master/tutorials/CSV_Analysis_Example.ipynb) and I was able to use execute the example code. When I changed the signal path to a different CSV file with my own data, it outputted a table of the first part of the data as expected. However, when I attempted to analyze the data using the pipeline in the second half of the code, I received the error message shown below.

### What I Did

```
from orion.analysis import analyze

hyperparameters = {
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

pipeline = 'lstm_dynamic_threshold'

anomalies = analyze(pipeline, data, hyperparams=hyperparameters)
anomalies

ERROR:mlblocks.mlpipeline:Exception caught fitting MLBlock keras.Sequential.LSTMTimeSeriesRegressor#1
Traceback (most recent call last):
  File "C:\Users\elias\anaconda3\envs\orion\lib\site-packages\mlblocks\mlpipeline.py", line 644, in _fit_block
    block.fit(**fit_args)
  File "C:\Users\elias\anaconda3\envs\orion\lib\site-packages\mlblocks\mlblock.py", line 311, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "C:\Users\elias\anaconda3\envs\orion\lib\site-packages\mlstars\adapters\keras.py", line 104, in fit
    self._augment_hyperparameters(X, 'input', kwargs)
  File "C:\Users\elias\anaconda3\envs\orion\lib\site-packages\mlstars\adapters\keras.py", line 90, in _augment_hyperparameters
    shape = np.asarray(X)[0].shape
IndexError: index 0 is out of bounds for axis 0 with size 0
```
From what I can tell, the only difference between my data and the example data is the values so I don't know why the code works for one but not the other.
Thank you for the help!

**Comment by sarahmish** [comment]
Hi @eliashyatt, thank you for using Orion!

It's necessary to change the hyperparameters of the pipeline to adapt to custom data. Please refer to the documentation on using [Pipeline with Custom Data](https://sintel.dev/Orion/user_guides/primitives_pipelines/pipelines.html#pipelines-for-custom-data).

Primarily, you need to change the `interval` setting to reflect the sampling frequency in your data.

Let me know if you have any further question!

**Comment by eliashyatt** [comment]
@sarahmish changing the interval worked. Thank you so much for your help!
