### ISSUE TITLE
Point Anomaly Setting for CSV Analysis

### ISSUE THREAD

**Issue by eliashyatt** [sintel-dev/Orion#509]
* Orion version: 0.5.1
* Python version: 3.8.18
* Operating System: Windows 10

### Description

I've been using the [CSV Analysis code](https://github.com/sintel-dev/Orion/blob/master/tutorials/CSV_Analysis_Example.ipynb) on some custom data that has an interval of 1 second, and I noticed that whenever it detects anomalies, it gives time values as a range of about 100 seconds. Since there are a lot of times in which anomalies are limited to one point, I was wondering if there was a way to change the settings so that I could see the single time value of a point anomaly.
Thank you!

**Comment by sarahmish** [comment]
Hi @eliashyatt - definitely!

There is a hyperparameter called `anomaly_padding` that defines how many data points to include before and after the point that was considered anomalous. To remove any padding, set the value to zero

```python3
hyperparameters = {
    'orion.primitives.timeseries_anomalies.find_anomalies#1': {
        'anomaly_padding': 0 # set to 50 by default
    }
}
```

for more information, visit the primitive page for [find_anomalies](https://sintel.dev/Orion/user_guides/primitives_pipelines/primitives/find_anomalies.html).

**Comment by eliashyatt** [comment]
Hi @sarahmish, thank you so much for the help!
