### ISSUE TITLE
type object 'Conv1D' has no attribute 'UpSampling1D'

### ISSUE THREAD

**Issue by OsYky** [sintel-dev/Orion#560]
My code：
tgan = TadGAN(**hyperparameters)
tgan.fit(X, y)

There is a following error when  trying to use tadgan：
type object 'Conv1D' has no attribute 'UpSampling1D'

However, I can't find anything like "Conv1D.UpSampling1D" code in the program. 
Can someone please help me, I'm a rookie Q_Q

**Comment by sarahmish** [comment]
Hi @OsYky – thank you for using Orion!

That error is unexpected, can you share which version of Orion and tensorflow you have installed? you can check by running:
```python3
import orion
import tensorflow as tf

print("orion version", orion.__version__)
print("tensorflow version", tf.__version__)
```

I tested the version provided on google colab ([link](https://colab.research.google.com/drive/1TVNK6HroahDeFFl06oOFYISt5JLLSSLO?ouid=101325702792223253477&usp=drive_link)), and it worked for me
