### ISSUE TITLE
README uses 'aer'

### ISSUE THREAD

**Issue by casper-voltgoed** [sintel-dev/Orion#562]
In the readme you have this sample of code:
```
orion = Orion(pipeline='aer', hyperparameters=hyperparameters)
```

But this gives an error that pipeline with that name does not exist. Apparently it should be 'AER'. So the code snippet should be updated.

**Comment by sarahmish** [comment]
Hi @casper-voltgoed - that's interesting, can you let me know which OS you're running on + python version.

The name of the pipeline is `aer` in lower case, and it should be easy to see what pipelines are available by running:
```python3
from mlblocks import get_pipelines_paths

get_pipelines_paths()
```
you should see a path close to `'path/to/python/site-packages/orion/pipelines/verified/aer'`

**Comment by casper-voltgoed** [comment]
Very odd, I just tried reproducing it and now it didn't occur. I might have had installed an old version or a wrong numpy version..?
