### ISSUE TITLE
Getting Axis error on uploading custom dataset of same dimension for AER pipeline

### ISSUE THREAD

**Issue by Kushpatel49** [sintel-dev/Orion#586]
### Description

Trying to run the colab available to use for custom data (2-Using Orion on Custom Data.ipynb) 

### What I Did

Shaped the data as per the instructions only two columns of timestamp and values with shape (20000,2).

sample data :

timestamp	value
1732166720	-0.000146
1732006034	-0.000258
1732189006	-0.000136
1732115532	-0.000060
1732078785	-0.000144

```
from orion import Orion

hyperparameters = { # alter the hyperparameter settings here
    'mlstars.custom.timeseries_preprocessing.time_segments_aggregate#1': {
        'interval': 21600
    },
    'orion.primitives.aer.AER#1': {
        'epochs': 5,
        'verbose': True
    }
}

orion = Orion(
    pipeline='aer',
    hyperparameters=hyperparameters
)

orion.fit(data)
```
on the execution of this cell i got 

ERROR:mlblocks.mlpipeline:Exception caught producing MLBlock orion.primitives.timeseries_preprocessing.slice_array_by_dims#1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mlblocks/mlpipeline.py", line 679, in _produce_block
    block_outputs = block.produce(**produce_args)
  File "/usr/local/lib/python3.10/dist-packages/mlblocks/mlblock.py", line 334, in produce
    return self.primitive(**produce_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/orion/primitives/timeseries_preprocessing.py", line 29, in slice_array_by_dims
    raise ValueError("Axis {} is outside the dimensions of X ({}).".format(axis, dims))
ValueError: Axis 2 is outside the dimensions of X (1).

ValueError                                Traceback (most recent call last)
[<ipython-input-91-43800a130f4e>](https://localhost:8080/#) in <cell line: 18>()
     16 )
     17 
---> 18 orion.fit(data)

4 frames
[/usr/local/lib/python3.10/dist-packages/orion/core.py](https://localhost:8080/#) in fit(self, data, **kwargs)
    109             self._mlpipeline = self._get_mlpipeline()
    110 
--> 111         self._mlpipeline.fit(data, **kwargs)
    112         self._fitted = True
    113 

[/usr/local/lib/python3.10/dist-packages/mlblocks/mlpipeline.py](https://localhost:8080/#) in fit(self, X, y, output_, start_, debug, **kwargs)
    803 
    804             if fit_pending or output_blocks:
--> 805                 self._produce_block(
    806                     block, block_name, context, output_variables, outputs, debug_info)
    807 

[/usr/local/lib/python3.10/dist-packages/mlblocks/mlpipeline.py](https://localhost:8080/#) in _produce_block(self, block, block_name, context, output_variables, outputs, debug_info)
    677             memory_before = process.memory_info().rss
    678             start = datetime.utcnow()
--> 679             block_outputs = block.produce(**produce_args)
    680             elapsed = datetime.utcnow() - start
    681             memory_after = process.memory_info().rss

[/usr/local/lib/python3.10/dist-packages/mlblocks/mlblock.py](https://localhost:8080/#) in produce(self, **kwargs)
    332 
    333         produce_kwargs.update(self.get_hyperparameters())
--> 334         return self.primitive(**produce_kwargs)

[/usr/local/lib/python3.10/dist-packages/orion/primitives/timeseries_preprocessing.py](https://localhost:8080/#) in slice_array_by_dims(X, target_index, axis)
     27     dims = len(X.shape)
     28     if axis >= (dims):
---> 29         raise ValueError("Axis {} is outside the dimensions of X ({}).".format(axis, dims))
     30 
     31     indices = [slice(None)] * dims

ValueError: Axis 2 is outside the dimensions of X (1).

**Comment by sarahmish** [comment]
Hi @Kushpatel49! Thank you for using Orion!

When using custom data, make sure to change the `interval` parameter to a value suitable for your data. The sample data does not seem to be sorted, so it's hard to know exactly what the space between one timestamp and another is.

See our [documentation](https://sintel.dev/Orion/user_guides/primitives_pipelines/pipelines.html#pipelines-for-custom-data).

**Comment by Kushpatel49** [comment]
Thanks It's working now.
